import {
  AUTO_VIDEO_ATTRIBUTE,
  CMS_ATTRIBUTE_ATTRIBUTE,
  CMS_COMBINE_ATTRIBUTE,
  CMS_CORE,
  CMS_FILTER_ATTRIBUTE,
  CMS_LOAD_ATTRIBUTE,
  CMS_NEST_ATTRIBUTE,
  CMS_SELECT_ATTRIBUTE,
  CMS_SLIDER_ATTRIBUTE,
  CMS_STATIC_ATTRIBUTE,
  CMS_SORT_ATTRIBUTE,
  CMS_TABS_ATTRIBUTE,
  CMS_PREV_NEXT_ATTRIBUTE,
  CODE_HIGHLIGHT_ATTRIBUTE,
  COPY_CLIP_ATTRIBUTE,
  COUNT_ITEMS_ATTRIBUTE,
  RANGE_SLIDER_ATTRIBUTE,
  RICH_TEXT_ATTRIBUTE,
  TOC_ATTRIBUTE,
  SCROLL_DISABLE_ATTRIBUTE,
  SELECT_CUSTOM_ATTRIBUTE,
  SLIDER_DOTS_ATTRIBUTE,
  SMART_LIGHTBOX_ATTRIBUTE,
  SOCIAL_SHARE_ATTRIBUTE,
  FORM_SUBMIT_ATTRIBUTE,
  LINK_BLOCK_EDIT_ATTRIBUTE,
  MIRROR_CLICK_ATTRIBUTE,
  MIRROR_INPUT_ATTRIBUTE,
  FAV_CUSTOM_ATTRIBUTE,
  QUERY_PARAM_ATTRIBUTE,
} from '@global/constants/attributes';

import type { AttributesData } from '../src/utils/types';

export const attributesData: AttributesData = [
  {
    key: AUTO_VIDEO_ATTRIBUTE,
    title: 'Auto Video',
    description:
      'All videos on the page (Background Video components & <video> elements used in HTML Embeds) play and pause based on if the video is visible in the viewport.',
    href: 'https://www.finsweet.com/attributes/auto-video',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-autovideo@1',
    scriptSrc: 'autovideo.js',
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: false,
  },
  {
    key: CMS_ATTRIBUTE_ATTRIBUTE,
    title: 'CMS Attribute',
    description: 'Apply custom attributes with CMS fields. Use with CMS Collection List and Template page.',
    href: 'https://www.finsweet.com/attributes/cms-attribute',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-cmsattribute@1',
    scriptSrc: 'cmsattribute.js',
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    schemaSrc: 'schema.json',
    allowSupport: true,
  },
  {
    key: CMS_COMBINE_ATTRIBUTE,
    title: 'CMS Combine',
    description:
      'Take multiple Collection Lists from different Collections and Combine them to one single Collection List.',
    href: 'https://www.finsweet.com/attributes/cms-combine',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-cmscombine@1',
    scriptSrc: 'cmscombine.js',
    examplesSrc: 'examples.json',
    loadMode: 'async',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: CMS_CORE,
    title: 'CMS Core',
    description: 'Core functionalities of all cms Attributes.',
    href: 'https://www.finsweet.com/attributes/api/cms-core',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-cmscore@1',
    scriptSrc: 'cmscore.js',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: false,
  },
  {
    key: CMS_FILTER_ATTRIBUTE,
    title: 'CMS Filter',
    description: 'Create advanced and complex no-code filter systems for Webflow CMS Collection List content.',
    href: 'https://www.finsweet.com/attributes/cms-filter',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-cmsfilter@1',
    scriptSrc: 'cmsfilter.js',
    examplesSrc: 'examples.json',
    loadMode: 'async',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: CMS_LOAD_ATTRIBUTE,
    title: 'CMS Load',
    description:
      'Set up powerful load functionality on Webflow CMS Collection Lists. Load items under, infinite scroll, pagination, and render all items.',
    href: 'https://www.finsweet.com/attributes/cms-load',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-cmsload@1',
    scriptSrc: 'cmsload.js',
    loadMode: 'async',
    examplesSrc: 'examples.json',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: CMS_NEST_ATTRIBUTE,
    title: 'CMS Nest',
    description:
      'Option to have no limitations for Webflow CMS Nested Collections. Nest more than 5 items. Nest multiple Collections on a page.',
    href: 'https://www.finsweet.com/attributes/cms-nest',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-cmsnest@1',
    scriptSrc: 'cmsnest.js',
    examplesSrc: 'examples.json',
    loadMode: 'async',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: CMS_PREV_NEXT_ATTRIBUTE,
    title: 'CMS PrevNext',
    description: 'Add Previous and Next buttons in Collection Template Pages.',
    href: 'https://www.finsweet.com/attributes/cms-prevnext',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-cmsprevnext@1',
    scriptSrc: 'cmsprevnext.js',
    examplesSrc: 'examples.json',
    loadMode: 'async',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: CMS_SELECT_ATTRIBUTE,
    title: 'CMS Select',
    description: 'Create dynamic Form Select element with Webflow CMS Collection List.',
    href: 'https://www.finsweet.com/attributes/cms-select',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-cmsselect@1',
    scriptSrc: 'cmsselect.js',
    examplesSrc: 'examples.json',
    loadMode: 'async',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: CMS_SLIDER_ATTRIBUTE,
    title: 'CMS Slider',
    description: 'Create a CMS powered native Webflow Slider component with a Webflow CMS Collection List.',
    href: 'https://www.finsweet.com/attributes/cms-slider',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-cmsslider@1',
    scriptSrc: 'cmsslider.js',
    examplesSrc: 'examples.json',
    loadMode: 'async',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: CMS_STATIC_ATTRIBUTE,
    title: 'CMS Static',
    description: 'Inject static content anywhere in a Webflow CMS Collection List.',
    href: 'https://www.finsweet.com/attributes/static-to-collection-list',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-cmsstatic@1',
    scriptSrc: 'cmsstatic.js',
    examplesSrc: 'examples.json',
    loadMode: 'async',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: CMS_SORT_ATTRIBUTE,
    title: 'CMS Sort',
    description: 'Create advanced and complex no-code sorting for Webflow CMS Collection List content.',
    href: 'https://www.finsweet.com/attributes/cms-sort',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-cmssort@1',
    scriptSrc: 'cmssort.js',
    examplesSrc: 'examples.json',
    loadMode: 'async',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: CMS_TABS_ATTRIBUTE,
    title: 'CMS Tabs',
    description: 'Create a CMS powered native Webflow Tabs component with a Webflow CMS Collection List.',
    href: 'https://www.finsweet.com/attributes/cms-tabs',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-cmstabs@1',
    scriptSrc: 'cmstabs.js',
    examplesSrc: 'examples.json',
    loadMode: 'async',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: CODE_HIGHLIGHT_ATTRIBUTE,
    title: 'Code Highlight',
    description: 'Display code with syntax highlighting.',
    href: 'https://www.finsweet.com/attributes/code-highlight',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-codehighlight@1',
    scriptSrc: 'codehighlight.js',
    examplesSrc: 'examples.json',
    loadMode: 'async',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: COPY_CLIP_ATTRIBUTE,
    title: 'Copy to clipboard',
    description: 'Set any element to copy a string value to the clipboard when clicking on it.',
    href: 'https://www.finsweet.com/attributes/copy-to-clipboard',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-copyclip@1',
    scriptSrc: 'copyclip.js',
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: FORM_SUBMIT_ATTRIBUTE,
    title: 'Form Submit Actions',
    description: 'Run smart actions after Webflow forms submission.',
    href: 'https://www.finsweet.com/attributes/form-submit',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-formsubmit@1',
    scriptSrc: 'formsubmit.js',
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: SCROLL_DISABLE_ATTRIBUTE,
    title: 'Disable scrolling',
    description: 'Prevent the page from scrolling when a element is clicked or visible.',
    href: 'https://www.finsweet.com/attributes/disable-scrolling',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-scrolldisable@1',
    scriptSrc: 'scrolldisable.js',
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: SELECT_CUSTOM_ATTRIBUTE,
    title: 'Custom Form Select',
    description: 'Use a Webflow Dropdown element as a Webflow Form <select> component.',
    href: 'https://www.finsweet.com/attributes/custom-form-select',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-selectcustom@1',
    scriptSrc: 'selectcustom.js',
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: SLIDER_DOTS_ATTRIBUTE,
    title: 'Custom slider dots',
    description: 'Populate the native slider dots with any content.',
    href: 'https://www.finsweet.com/attributes/custom-slider-dots',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-sliderdots@1',
    scriptSrc: 'sliderdots.js',
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: LINK_BLOCK_EDIT_ATTRIBUTE,
    title: 'Link blocks in editor',
    description: 'Convert Div Blocks to accessible Link Blocks that can be edited in the Editor.',
    href: 'https://www.finsweet.com/attributes/edit-link-blocks-in-editor',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-linkblockedit@1',
    scriptSrc: 'linkblockedit.js',
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: MIRROR_CLICK_ATTRIBUTE,
    title: 'Mirror click events',
    description: 'Mirror click events between a trigger and a target.',
    href: 'https://www.finsweet.com/attributes/mirror-click-events',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-mirrorclick@1',
    scriptSrc: 'mirrorclick.js',
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: MIRROR_INPUT_ATTRIBUTE,
    title: 'Mirror input values',
    description: 'Mirror input events between a trigger and a target.',
    href: 'https://www.finsweet.com/attributes/mirror-input-values',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-mirrorinput@1',
    scriptSrc: 'mirrorinput.js',
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: RANGE_SLIDER_ATTRIBUTE,
    title: 'Range Slider',
    description: 'Build a custom Range Slider Form component natively in Webflow.',
    href: 'https://www.finsweet.com/attributes/range-slider',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-rangeslider@1',
    scriptSrc: 'rangeslider.js',
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: RICH_TEXT_ATTRIBUTE,
    title: 'Powerful Rich Text',
    description:
      'Add HTML to Rich Text elements, add components from the same page or from different pages, add classes, ids, attributes, and more.',
    href: 'https://www.finsweet.com/attributes/powerful-rich-text',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-richtext@1',
    scriptSrc: 'richtext.js',
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: SMART_LIGHTBOX_ATTRIBUTE,
    title: 'Smart Lightbox',
    description:
      'Change the position of an opened lightbox to prevent unwanted `z-index`, `fixed` positioning, and `transform` issues.',
    href: 'https://www.finsweet.com/attributes/smart-lightbox',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-smartlightbox@1',
    scriptSrc: 'smartlightbox.js',
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: COUNT_ITEMS_ATTRIBUTE,
    title: 'List item counter',
    description: 'Display the amount of children from an element.',
    href: 'https://www.finsweet.com/attributes/count-list-items',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-countitems@1',
    scriptSrc: 'countitems.js',
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: FAV_CUSTOM_ATTRIBUTE,
    title: 'Custom favicon by page',
    description: 'Customize the Favicon for a specific page.',
    href: 'https://www.finsweet.com/attributes/custom-fav-icon-by-page',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-favcustom@1',
    scriptSrc: 'favcustom.js',
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: TOC_ATTRIBUTE,
    title: 'Table of Contents',
    description:
      'Automatically generate a table of contents based on heading tags. Works with Webflow Rich Text, Webflow "Current" class, and anchor scroll. CMS, static, and all text elements are supported.',
    href: 'https://www.finsweet.com/attributes/table-of-contents',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-toc@1',
    scriptSrc: 'toc.js',
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: SOCIAL_SHARE_ATTRIBUTE,
    title: 'Social Share',
    description: 'Share content to social media platforms. Works with Collection Lists, Templates, and static content.',
    href: 'https://www.finsweet.com/attributes/social-share',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-socialshare@1',
    scriptSrc: 'socialshare.js',
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: QUERY_PARAM_ATTRIBUTE,
    title: 'Query Param',
    description: 'Use query parameter values to populate form inputs and text elements.',
    href: 'https://www.finsweet.com/attributes/query-param',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-queryparam@1',
    scriptSrc: 'queryparam.js',
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
];
