import {
  A11Y_ATTRIBUTE,
  ACCORDION_ATTRIBUTE,
  AUTO_VIDEO_ATTRIBUTE,
  CMS_ATTRIBUTE_ATTRIBUTE,
  CMS_COMBINE_ATTRIBUTE,
  CMS_CORE_ATTRIBUTE,
  CMS_FILTER_ATTRIBUTE,
  CMS_LOAD_ATTRIBUTE,
  CMS_NEST_ATTRIBUTE,
  CMS_PREV_NEXT_ATTRIBUTE,
  CMS_SELECT_ATTRIBUTE,
  CMS_SLIDER_ATTRIBUTE,
  CMS_SORT_ATTRIBUTE,
  CMS_STATIC_ATTRIBUTE,
  CMS_TABS_ATTRIBUTE,
  CODE_HIGHLIGHT_ATTRIBUTE,
  COPY_CLIP_ATTRIBUTE,
  COUNT_ITEMS_ATTRIBUTE,
  DOCS_ATTRIBUTE,
  FAV_CUSTOM_ATTRIBUTE,
  FORM_SUBMIT_ATTRIBUTE,
  INPUT_ACTIVE_ATTRIBUTE,
  INPUT_COUNTER_ATTRIBUTE,
  LINK_BLOCK_EDIT_ATTRIBUTE,
  MIRROR_CLICK_ATTRIBUTE,
  MIRROR_INPUT_ATTRIBUTE,
  MODAL_ATTRIBUTE,
  NUMBER_COUNT_ATTRIBUTE,
  QUERY_PARAM_ATTRIBUTE,
  RANGE_SLIDER_ATTRIBUTE,
  READ_TIME_ATTRIBUTE,
  RICH_TEXT_ATTRIBUTE,
  SCROLL_DISABLE_ATTRIBUTE,
  SELECT_CUSTOM_ATTRIBUTE,
  SLIDER_DOTS_ATTRIBUTE,
  SMART_LIGHTBOX_ATTRIBUTE,
  SOCIAL_SHARE_ATTRIBUTE,
  STAR_RATING_ATTRIBUTE,
  TOC_ATTRIBUTE,
  VIDEO_HLS_ATTRIBUTE,
} from '$global/constants/attributes';

import type { AttributesData } from '../src/utils/types';

const createDocsHref = (pathname: string) => `https://www.finsweet.com/attributes/${pathname}`;

const attributesData: AttributesData = [
  {
    key: AUTO_VIDEO_ATTRIBUTE,
    title: 'Auto Video',
    description:
      'All videos on the page (Background Video components & <video> elements used in HTML Embeds) play and pause based on if the video is visible in the viewport.',
    href: createDocsHref('auto-video'),
    baseSrc: `https://cdn.jsdelivr.net/npm/@finsweet/attributes-${AUTO_VIDEO_ATTRIBUTE}@1`,
    scriptSrc: `${AUTO_VIDEO_ATTRIBUTE}.js`,
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: false,
  },
  {
    key: CMS_ATTRIBUTE_ATTRIBUTE,
    title: 'CMS Attribute',
    description: 'Apply custom attributes with CMS fields. Use with CMS Collection List and Template page.',
    href: createDocsHref('cms-attribute'),
    baseSrc: `https://cdn.jsdelivr.net/npm/@finsweet/attributes-${CMS_ATTRIBUTE_ATTRIBUTE}@1`,
    scriptSrc: `${CMS_ATTRIBUTE_ATTRIBUTE}.js`,
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    schemaSrc: 'schema.json',
    allowSupport: true,
  },
  {
    key: CMS_COMBINE_ATTRIBUTE,
    title: 'CMS Combine',
    description:
      'Take multiple Collection Lists from different Collections and Combine them to one single Collection List.',
    href: createDocsHref('cms-combine'),
    baseSrc: `https://cdn.jsdelivr.net/npm/@finsweet/attributes-${CMS_COMBINE_ATTRIBUTE}@1`,
    scriptSrc: `${CMS_COMBINE_ATTRIBUTE}.js`,
    examplesSrc: 'examples.json',
    loadMode: 'async',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: CMS_CORE_ATTRIBUTE,
    title: 'CMS Core',
    description: 'Core functionalities of all cms Attributes.',
    href: createDocsHref('api/cms-core'),
    baseSrc: `https://cdn.jsdelivr.net/npm/@finsweet/attributes-${CMS_CORE_ATTRIBUTE}@1`,
    scriptSrc: `${CMS_CORE_ATTRIBUTE}.js`,
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: false,
  },
  {
    key: CMS_FILTER_ATTRIBUTE,
    title: 'CMS Filter',
    description: 'Create advanced and complex no-code filter systems for Webflow CMS Collection List content.',
    href: createDocsHref('cms-filter'),
    baseSrc: `https://cdn.jsdelivr.net/npm/@finsweet/attributes-${CMS_FILTER_ATTRIBUTE}@1`,
    scriptSrc: `${CMS_FILTER_ATTRIBUTE}.js`,
    examplesSrc: 'examples.json',
    loadMode: 'async',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: CMS_LOAD_ATTRIBUTE,
    title: 'CMS Load',
    description:
      'Set up powerful load functionality on Webflow CMS Collection Lists. Load items under, infinite scroll, pagination, and render all items.',
    href: createDocsHref('cms-load'),
    baseSrc: `https://cdn.jsdelivr.net/npm/@finsweet/attributes-${CMS_LOAD_ATTRIBUTE}@1`,
    scriptSrc: `${CMS_LOAD_ATTRIBUTE}.js`,
    loadMode: 'async',
    examplesSrc: 'examples.json',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: CMS_NEST_ATTRIBUTE,
    title: 'CMS Nest',
    description:
      'Option to have no limitations for Webflow CMS Nested Collections. Nest more than 5 items. Nest multiple Collections on a page.',
    href: createDocsHref('cms-nest'),
    baseSrc: `https://cdn.jsdelivr.net/npm/@finsweet/attributes-${CMS_NEST_ATTRIBUTE}@1`,
    scriptSrc: `${CMS_NEST_ATTRIBUTE}.js`,
    examplesSrc: 'examples.json',
    loadMode: 'async',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: CMS_PREV_NEXT_ATTRIBUTE,
    title: 'CMS PrevNext',
    description: 'Add Previous and Next buttons in Collection Template Pages.',
    href: createDocsHref('cms-prevnext'),
    baseSrc: `https://cdn.jsdelivr.net/npm/@finsweet/attributes-${CMS_PREV_NEXT_ATTRIBUTE}@1`,
    scriptSrc: `${CMS_PREV_NEXT_ATTRIBUTE}.js`,
    examplesSrc: 'examples.json',
    loadMode: 'async',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: CMS_SELECT_ATTRIBUTE,
    title: 'CMS Select',
    description: 'Create dynamic Form Select element with Webflow CMS Collection List.',
    href: createDocsHref('cms-select'),
    baseSrc: `https://cdn.jsdelivr.net/npm/@finsweet/attributes-${CMS_SELECT_ATTRIBUTE}@1`,
    scriptSrc: `${CMS_SELECT_ATTRIBUTE}.js`,
    examplesSrc: 'examples.json',
    loadMode: 'async',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: CMS_SLIDER_ATTRIBUTE,
    title: 'CMS Slider',
    description: 'Create a CMS powered native Webflow Slider component with a Webflow CMS Collection List.',
    href: createDocsHref('cms-slider'),
    baseSrc: `https://cdn.jsdelivr.net/npm/@finsweet/attributes-${CMS_SLIDER_ATTRIBUTE}@1`,
    scriptSrc: `${CMS_SLIDER_ATTRIBUTE}.js`,
    examplesSrc: 'examples.json',
    loadMode: 'async',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: CMS_STATIC_ATTRIBUTE,
    title: 'CMS Static',
    description: 'Inject static content anywhere in a Webflow CMS Collection List.',
    href: createDocsHref('static-to-collection-list'),
    baseSrc: `https://cdn.jsdelivr.net/npm/@finsweet/attributes-${CMS_STATIC_ATTRIBUTE}@1`,
    scriptSrc: `${CMS_STATIC_ATTRIBUTE}.js`,
    examplesSrc: 'examples.json',
    loadMode: 'async',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: CMS_SORT_ATTRIBUTE,
    title: 'CMS Sort',
    description: 'Create advanced and complex no-code sorting for Webflow CMS Collection List content.',
    href: createDocsHref('cms-sort'),
    baseSrc: `https://cdn.jsdelivr.net/npm/@finsweet/attributes-${CMS_SORT_ATTRIBUTE}@1`,
    scriptSrc: `${CMS_SORT_ATTRIBUTE}.js`,
    examplesSrc: 'examples.json',
    loadMode: 'async',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: CMS_TABS_ATTRIBUTE,
    title: 'CMS Tabs',
    description: 'Create a CMS powered native Webflow Tabs component with a Webflow CMS Collection List.',
    href: createDocsHref('cms-tabs'),
    baseSrc: `https://cdn.jsdelivr.net/npm/@finsweet/attributes-${CMS_TABS_ATTRIBUTE}@1`,
    scriptSrc: `${CMS_TABS_ATTRIBUTE}.js`,
    examplesSrc: 'examples.json',
    loadMode: 'async',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: CODE_HIGHLIGHT_ATTRIBUTE,
    title: 'Code Highlight',
    description: 'Display code with syntax highlighting.',
    href: createDocsHref('code-highlight'),
    baseSrc: `https://cdn.jsdelivr.net/npm/@finsweet/attributes-${CODE_HIGHLIGHT_ATTRIBUTE}@1`,
    scriptSrc: `${CODE_HIGHLIGHT_ATTRIBUTE}.js`,
    examplesSrc: 'examples.json',
    loadMode: 'async',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: COPY_CLIP_ATTRIBUTE,
    title: 'Copy to clipboard',
    description: 'Set any element to copy a string value to the clipboard when clicking on it.',
    href: createDocsHref('copy-to-clipboard'),
    baseSrc: `https://cdn.jsdelivr.net/npm/@finsweet/attributes-${COPY_CLIP_ATTRIBUTE}@1`,
    scriptSrc: `${COPY_CLIP_ATTRIBUTE}.js`,
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: DOCS_ATTRIBUTE,
    title: 'Docs',
    description: 'Internal logic for the Attributes documentation.',
    href: createDocsHref(''),
    baseSrc: `https://cdn.jsdelivr.net/npm/@finsweet/attributes-${DOCS_ATTRIBUTE}@1`,
    scriptSrc: `${DOCS_ATTRIBUTE}.js`,
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: false,
  },
  {
    key: FORM_SUBMIT_ATTRIBUTE,
    title: 'Form Submit Actions',
    description: 'Run smart actions after Webflow forms submission.',
    href: createDocsHref('form-submit'),
    baseSrc: `https://cdn.jsdelivr.net/npm/@finsweet/attributes-${FORM_SUBMIT_ATTRIBUTE}@1`,
    scriptSrc: `${FORM_SUBMIT_ATTRIBUTE}.js`,
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: SCROLL_DISABLE_ATTRIBUTE,
    title: 'Disable scrolling',
    description: 'Prevent the page from scrolling when a element is clicked or visible.',
    href: createDocsHref('disable-scrolling'),
    baseSrc: `https://cdn.jsdelivr.net/npm/@finsweet/attributes-${SCROLL_DISABLE_ATTRIBUTE}@1`,
    scriptSrc: `${SCROLL_DISABLE_ATTRIBUTE}.js`,
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: SELECT_CUSTOM_ATTRIBUTE,
    title: 'Custom Form Select',
    description: 'Use a Webflow Dropdown element as a Webflow Form <select> component.',
    href: createDocsHref('custom-form-select'),
    baseSrc: `https://cdn.jsdelivr.net/npm/@finsweet/attributes-${SELECT_CUSTOM_ATTRIBUTE}@1`,
    scriptSrc: `${SELECT_CUSTOM_ATTRIBUTE}.js`,
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: SLIDER_DOTS_ATTRIBUTE,
    title: 'Custom slider dots',
    description: 'Populate the native slider dots with any content.',
    href: createDocsHref('custom-slider-dots'),
    baseSrc: `https://cdn.jsdelivr.net/npm/@finsweet/attributes-${SLIDER_DOTS_ATTRIBUTE}@1`,
    scriptSrc: `${SLIDER_DOTS_ATTRIBUTE}.js`,
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: LINK_BLOCK_EDIT_ATTRIBUTE,
    title: 'Link blocks in editor',
    description: 'Convert Div Blocks to accessible Link Blocks that can be edited in the Editor.',
    href: createDocsHref('edit-link-blocks-in-editor'),
    baseSrc: `https://cdn.jsdelivr.net/npm/@finsweet/attributes-${LINK_BLOCK_EDIT_ATTRIBUTE}@1`,
    scriptSrc: `${LINK_BLOCK_EDIT_ATTRIBUTE}.js`,
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: MIRROR_CLICK_ATTRIBUTE,
    title: 'Mirror click events',
    description: 'Mirror click events between a trigger and a target.',
    href: createDocsHref('mirror-click-events'),
    baseSrc: `https://cdn.jsdelivr.net/npm/@finsweet/attributes-${MIRROR_CLICK_ATTRIBUTE}@1`,
    scriptSrc: `${MIRROR_CLICK_ATTRIBUTE}.js`,
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: MIRROR_INPUT_ATTRIBUTE,
    title: 'Mirror input values',
    description: 'Mirror input events between a trigger and a target.',
    href: createDocsHref('mirror-input-values'),
    baseSrc: `https://cdn.jsdelivr.net/npm/@finsweet/attributes-${MIRROR_INPUT_ATTRIBUTE}@1`,
    scriptSrc: `${MIRROR_INPUT_ATTRIBUTE}.js`,
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: NUMBER_COUNT_ATTRIBUTE,
    title: 'Number Count',
    description: 'Create a number count animation in Webflow.',
    href: createDocsHref('number-count'),
    baseSrc: `https://cdn.jsdelivr.net/npm/@finsweet/attributes-${NUMBER_COUNT_ATTRIBUTE}@1`,
    scriptSrc: `${NUMBER_COUNT_ATTRIBUTE}.js`,
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: false,
  },
  {
    key: RANGE_SLIDER_ATTRIBUTE,
    title: 'Range Slider',
    description: 'Build a custom Range Slider Form component natively in Webflow.',
    href: createDocsHref('range-slider'),
    baseSrc: `https://cdn.jsdelivr.net/npm/@finsweet/attributes-${RANGE_SLIDER_ATTRIBUTE}@1`,
    scriptSrc: `${RANGE_SLIDER_ATTRIBUTE}.js`,
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: RICH_TEXT_ATTRIBUTE,
    title: 'Powerful Rich Text',
    description:
      'Add HTML to Rich Text elements, add components from the same page or from different pages, add classes, ids, attributes, and more.',
    href: createDocsHref('powerful-rich-text'),
    baseSrc: `https://cdn.jsdelivr.net/npm/@finsweet/attributes-${RICH_TEXT_ATTRIBUTE}@1`,
    scriptSrc: `${RICH_TEXT_ATTRIBUTE}.js`,
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: SMART_LIGHTBOX_ATTRIBUTE,
    title: 'Smart Lightbox',
    description:
      'Change the position of an opened lightbox to prevent unwanted `z-index`, `fixed` positioning, and `transform` issues.',
    href: createDocsHref('smart-lightbox'),
    baseSrc: `https://cdn.jsdelivr.net/npm/@finsweet/attributes-${SMART_LIGHTBOX_ATTRIBUTE}@1`,
    scriptSrc: `${SMART_LIGHTBOX_ATTRIBUTE}.js`,
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: COUNT_ITEMS_ATTRIBUTE,
    title: 'List item counter',
    description: 'Display the amount of children from an element.',
    href: createDocsHref('count-list-items'),
    baseSrc: `https://cdn.jsdelivr.net/npm/@finsweet/attributes-${COUNT_ITEMS_ATTRIBUTE}@1`,
    scriptSrc: `${COUNT_ITEMS_ATTRIBUTE}.js`,
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: FAV_CUSTOM_ATTRIBUTE,
    title: 'Custom favicon by page',
    description: 'Customize the Favicon for a specific page.',
    href: createDocsHref('custom-fav-icon-by-page'),
    baseSrc: `https://cdn.jsdelivr.net/npm/@finsweet/attributes-${FAV_CUSTOM_ATTRIBUTE}@1`,
    scriptSrc: `${FAV_CUSTOM_ATTRIBUTE}.js`,
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: TOC_ATTRIBUTE,
    title: 'Table of Contents',
    description:
      'Automatically generate a table of contents based on heading tags. Works with Webflow Rich Text, Webflow "Current" class, and anchor scroll. CMS, static, and all text elements are supported.',
    href: createDocsHref('table-of-contents'),
    baseSrc: `https://cdn.jsdelivr.net/npm/@finsweet/attributes-${TOC_ATTRIBUTE}@1`,
    scriptSrc: `${TOC_ATTRIBUTE}.js`,
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: READ_TIME_ATTRIBUTE,
    title: 'Read Time',
    description: 'Calculate and display the estimated read time of Rich Text content based on word count.',
    href: createDocsHref('read-time'),
    baseSrc: `https://cdn.jsdelivr.net/npm/@finsweet/attributes-${READ_TIME_ATTRIBUTE}@1`,
    scriptSrc: `${READ_TIME_ATTRIBUTE}.js`,
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: SOCIAL_SHARE_ATTRIBUTE,
    title: 'Social Share',
    description: 'Share content to social media platforms. Works with Collection Lists, Templates, and static content.',
    href: createDocsHref('social-share'),
    baseSrc: `https://cdn.jsdelivr.net/npm/@finsweet/attributes-${SOCIAL_SHARE_ATTRIBUTE}@1`,
    scriptSrc: `${SOCIAL_SHARE_ATTRIBUTE}.js`,
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: QUERY_PARAM_ATTRIBUTE,
    title: 'Query Param',
    description: 'Use query parameter values to populate form inputs and text elements.',
    href: createDocsHref('query-param'),
    baseSrc: `https://cdn.jsdelivr.net/npm/@finsweet/attributes-${QUERY_PARAM_ATTRIBUTE}@1`,
    scriptSrc: `${QUERY_PARAM_ATTRIBUTE}.js`,
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: INPUT_COUNTER_ATTRIBUTE,
    title: 'Input Counter',
    description: 'Increment and decrement (+ and -) counter in a Webflow Form.',
    href: createDocsHref('input-counter'),
    baseSrc: `https://cdn.jsdelivr.net/npm/@finsweet/attributes-${INPUT_COUNTER_ATTRIBUTE}@1`,
    scriptSrc: `${INPUT_COUNTER_ATTRIBUTE}.js`,
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: false,
  },
  {
    key: MODAL_ATTRIBUTE,
    title: 'Modal',
    description: 'Create accessible modal popups easily on Webflow.',
    href: createDocsHref('modal'),
    baseSrc: `https://cdn.jsdelivr.net/npm/@finsweet/attributes-${MODAL_ATTRIBUTE}@1`,
    scriptSrc: `${MODAL_ATTRIBUTE}.js`,
    examplesSrc: 'examples.json',
    loadMode: 'async',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: false,
  },
  {
    key: STAR_RATING_ATTRIBUTE,
    title: 'Star Rating',
    description: 'Star rating radio button component inside any Webflow form.',
    href: createDocsHref('star-rating'),
    baseSrc: `https://cdn.jsdelivr.net/npm/@finsweet/attributes-${STAR_RATING_ATTRIBUTE}@1`,
    scriptSrc: `${STAR_RATING_ATTRIBUTE}.js`,
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: false,
  },
  {
    key: ACCORDION_ATTRIBUTE,
    title: 'Accordion',
    description: 'Create accessible accordions inside Webflow without Webflow Interactions.',
    href: createDocsHref('accordion'),
    baseSrc: `https://cdn.jsdelivr.net/npm/@finsweet/attributes-${ACCORDION_ATTRIBUTE}@1`,
    scriptSrc: `${ACCORDION_ATTRIBUTE}.js`,
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: false,
  },
  {
    key: A11Y_ATTRIBUTE,
    title: 'Accessibility',
    description: "Improve your Webflow project's accessibility.",
    href: createDocsHref('accessibility-javascript'),
    baseSrc: `https://cdn.jsdelivr.net/npm/@finsweet/attributes-${A11Y_ATTRIBUTE}@1`,
    scriptSrc: `${A11Y_ATTRIBUTE}.js`,
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: false,
  },
  {
    key: INPUT_ACTIVE_ATTRIBUTE,
    title: 'Input Active Class',
    description: 'Set custom active CSS classes for Webflow form elements.',
    href: createDocsHref('input-active'),
    baseSrc: `https://cdn.jsdelivr.net/npm/@finsweet/attributes-${INPUT_ACTIVE_ATTRIBUTE}@1`,
    scriptSrc: `${INPUT_ACTIVE_ATTRIBUTE}.js`,
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: false,
  },
  {
    key: VIDEO_HLS_ATTRIBUTE,
    title: 'Video HLS',
    description: 'Implement hls.js to a Webflow project.',
    href: createDocsHref('video-hls'),
    baseSrc: `https://cdn.jsdelivr.net/npm/@finsweet/attributes-${VIDEO_HLS_ATTRIBUTE}@1`,
    scriptSrc: `${VIDEO_HLS_ATTRIBUTE}.js`,
    examplesSrc: 'examples.json',
    loadMode: 'async',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: false,
  },
];

export default attributesData;
