import type { AttributesData } from '../src/utils/types';

export const attributesData: AttributesData = [
  {
    key: 'autovideo',
    title: 'Auto Video',
    description:
      'All videos on the page (Background Video components & <video> elements used in HTML Embeds) play and pause based on if the video is visible in the viewport.',
    href: 'https://www.finsweet.com/attributes/auto-video',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-autovideo@1',
    scriptSrc: 'autovideo.js',
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: 'cmscombine',
    title: 'CMS Combine',
    description:
      'Take multiple Collection Lists from different Collections and Combine them to one single Collection List.',
    href: 'https://www.finsweet.com/attributes/cms-combine',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-cmscombine@1',
    scriptSrc: 'cmscombine.js',
    examplesSrc: 'examples.json',
    loadMode: 'async',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: 'cmscore',
    title: 'CMS Core',
    description: 'Core functionalities of all cms Attributes.',
    href: 'https://www.finsweet.com/attributes/api/cms-core',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-cmscore@1',
    scriptSrc: 'cmscore.js',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: false,
  },
  {
    key: 'cmsfilter',
    title: 'CMS Filter',
    description: 'Create advanced and complex no-code filter systems for Webflow CMS Collection List content.',
    href: 'https://www.finsweet.com/attributes/cms-filter',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-cmsfilter@1',
    scriptSrc: 'cmsfilter.js',
    examplesSrc: 'examples.json',
    loadMode: 'async',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: 'cmsload',
    title: 'CMS Load',
    description:
      'Set up powerful load functionality on Webflow CMS Collection Lists. Load items under, infinite scroll, pagination, and render all items.',
    href: 'https://www.finsweet.com/attributes/cms-load',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-cmsload@1',
    scriptSrc: 'cmsload.js',
    loadMode: 'async',
    examplesSrc: 'examples.json',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: 'cmsnest',
    title: 'CMS Nest',
    description:
      'Option to have no limitations for Webflow CMS Nested Collections. Nest more than 5 items. Nest multiple Collections on a page.',
    href: 'https://www.finsweet.com/attributes/cms-nest',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-cmsnest@1',
    scriptSrc: 'cmsnest.js',
    examplesSrc: 'examples.json',
    loadMode: 'async',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: 'cmsprevnext',
    title: 'CMS PrevNext',
    description: 'Add Previous and Next buttons in Collection Template Pages.',
    href: 'https://www.finsweet.com/attributes/cms-prevnext',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-cmsprevnext@1',
    scriptSrc: 'cmsprevnext.js',
    examplesSrc: 'examples.json',
    loadMode: 'async',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: 'cmsselect',
    title: 'CMS Select',
    description: 'Create dynamic Form Select element with Webflow CMS Collection List.',
    href: 'https://www.finsweet.com/attributes/cms-select',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-cmsselect@1',
    scriptSrc: 'cmsselect.js',
    examplesSrc: 'examples.json',
    loadMode: 'async',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: 'cmsslider',
    title: 'CMS Slider',
    description: 'Create a CMS powered native Webflow Slider component with a Webflow CMS Collection List.',
    href: 'https://www.finsweet.com/attributes/cms-slider',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-cmsslider@1',
    scriptSrc: 'cmsslider.js',
    examplesSrc: 'examples.json',
    loadMode: 'async',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: 'cmssort',
    title: 'CMS Sort',
    description: 'Create advanced and complex no-code sorting for Webflow CMS Collection List content.',
    href: 'https://www.finsweet.com/attributes/cms-sort',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-cmssort@1',
    scriptSrc: 'cmssort.js',
    examplesSrc: 'examples.json',
    loadMode: 'async',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: 'cmstabs',
    title: 'CMS Tabs',
    description: 'Create a CMS powered native Webflow Tabs component with a Webflow CMS Collection List.',
    href: 'https://www.finsweet.com/attributes/cms-tabs',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-cmstabs@1',
    scriptSrc: 'cmstabs.js',
    examplesSrc: 'examples.json',
    loadMode: 'async',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: 'codehighlight',
    title: 'Code Highlight',
    description: 'Display code with syntax highlighting.',
    href: 'https://www.finsweet.com/attributes/code-highlight',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-codehighlight@1',
    scriptSrc: 'codehighlight.js',
    examplesSrc: 'examples.json',
    loadMode: 'async',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: 'copyclip',
    title: 'Copy to clipboard',
    description: 'Set any element to copy a string value to the clipboard when clicking on it.',
    href: 'https://www.finsweet.com/attributes/copy-to-clipboard',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-copyclip@1',
    scriptSrc: 'copyclip.js',
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: 'scrolldisable',
    title: 'Disable scrolling',
    description: 'Prevent the page from scrolling when a element is clicked or visible.',
    href: 'https://www.finsweet.com/attributes/disable-scrolling',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-scrolldisable@1',
    scriptSrc: 'scrolldisable.js',
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: 'selectcustom',
    title: 'Custom Form Select',
    description: 'Use a Webflow Dropdown element as a Webflow Form <select> component.',
    href: 'https://www.finsweet.com/attributes/custom-form-select',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-selectcustom@1',
    scriptSrc: 'selectcustom.js',
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: 'sliderdots',
    title: 'Custom slider dots',
    description: 'Populate the native slider dots with any content.',
    href: 'https://www.finsweet.com/attributes/custom-slider-dots',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-sliderdots@1',
    scriptSrc: 'sliderdots.js',
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: 'linkblockedit',
    title: 'Link blocks in editor',
    description: 'Convert Div Blocks to accessible Link Blocks that can be edited in the Editor.',
    href: 'https://www.finsweet.com/attributes/edit-link-blocks-in-editor',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-linkblockedit@1',
    scriptSrc: 'linkblockedit.js',
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: 'mirrorclick',
    title: 'Mirror click events',
    description: 'Mirror click events between a trigger and a target.',
    href: 'https://www.finsweet.com/attributes/mirror-click-events',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-mirrorclick@1',
    scriptSrc: 'mirrorclick.js',
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: 'mirrorinput',
    title: 'Mirror input values',
    description: 'Mirror input events between a trigger and a target.',
    href: 'https://www.finsweet.com/attributes/mirror-input-values',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-mirrorinput@1',
    scriptSrc: 'mirrorinput.js',
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: 'rangeslider',
    title: 'Range Slider',
    description: 'Build a custom Range Slider Form component natively in Webflow.',
    href: 'https://www.finsweet.com/attributes/range-slider',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-rangeslider@1',
    scriptSrc: 'rangeslider.js',
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: 'richtext',
    title: 'Powerful Rich Text',
    description:
      'Add HTML to Rich Text elements, add components from the same page or from different pages, add classes, ids, attributes, and more.',
    href: 'https://www.finsweet.com/attributes/powerful-rich-text',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-richtext@1',
    scriptSrc: 'richtext.js',
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: 'smartlightbox',
    title: 'Smart Lightbox',
    description:
      'Change the position of an opened lightbox to prevent unwanted `z-index`, `fixed` positioning, and `transform` issues.',
    href: 'https://www.finsweet.com/attributes/smart-lightbox',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-smartlightbox@1',
    scriptSrc: 'smartlightbox.js',
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: 'countitems',
    title: 'List item counter',
    description: 'Display the amount of children from an element.',
    href: 'https://www.finsweet.com/attributes/count-list-items',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-countitems@1',
    scriptSrc: 'countitems.js',
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: 'favcustom',
    title: 'Custom favicon by page',
    description: 'Customize the Favicon for a specific page.',
    href: 'https://www.finsweet.com/attributes/custom-fav-icon-by-page',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-favcustom@1',
    scriptSrc: 'favcustom.js',
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
  {
    key: 'toc',
    title: 'Table of Contents',
    description:
      'Automatically generate a table of contents based on heading tags. Works with Webflow Rich Text, Webflow "Current" class, and anchor scroll. CMS, static, and all text elements are supported.',
    href: 'https://www.finsweet.com/attributes/table-of-contents',
    baseSrc: 'https://cdn.jsdelivr.net/npm/@finsweet/attributes-toc@1',
    scriptSrc: 'toc.js',
    examplesSrc: 'examples.json',
    loadMode: 'defer',
    schemaSrc: 'schema.json',
    changesetsSrc: 'changesets.json',
    readmeSrc: 'README.md',
    allowSupport: true,
  },
];
