import type { AttributeExamples } from '$global/types/examples';

const examples: AttributeExamples = [
  {
    title: 'Basic Input Counter',
    description: 'Increment and decrement (+ and -) counter in a Webflow Form.',
    data: {
      type: '@webflow/XscpData',
      payload: {
        nodes: [
          {
            _id: 'dbdb8996-1dfe-c7b5-c1a8-7c98b2addbc0',
            type: 'FormWrapper',
            tag: 'div',
            classes: [],
            children: [
              'dbdb8996-1dfe-c7b5-c1a8-7c98b2addbc1',
              'dbdb8996-1dfe-c7b5-c1a8-7c98b2addbc9',
              'dbdb8996-1dfe-c7b5-c1a8-7c98b2addbcc',
            ],
            data: {
              form: { type: 'wrapper' },
              displayName: '',
              attr: { id: '' },
              xattr: [],
              search: { exclude: true },
              visibility: { conditions: [] },
            },
          },
          {
            _id: 'dbdb8996-1dfe-c7b5-c1a8-7c98b2addbc1',
            type: 'FormForm',
            tag: 'form',
            classes: ['15888a7f-7f99-6aba-31a8-940baa3eff35'],
            children: [
              'e640c8c9-2047-8ad3-3311-ceeff314bb07',
              'dbdb8996-1dfe-c7b5-c1a8-7c98b2addbc4',
              'f46768e3-5fcc-1f9b-307f-442500c99761',
            ],
            data: {
              form: { type: 'form', name: 'Email Form' },
              search: { exclude: false },
              xattr: [],
              displayName: '',
              attr: {
                id: 'email-form',
                name: 'email-form',
                'data-name': 'Email Form',
                redirect: '',
                'data-redirect': '',
                action: '',
                method: 'get',
              },
              visibility: { conditions: [] },
              Source: { tag: 'Default form', val: {} },
            },
          },
          {
            _id: 'e640c8c9-2047-8ad3-3311-ceeff314bb07',
            type: 'Link',
            tag: 'a',
            classes: ['b0934d9a-875a-bb42-0630-12090a77fbf1'],
            children: ['e640c8c9-2047-8ad3-3311-ceeff314bb08'],
            data: {
              search: { exclude: true },
              xattr: [{ name: 'fs-inputcounter-element', value: 'decrement-1' }],
              block: '',
              displayName: '',
              devlink: { runtimeProps: {}, slot: '' },
              attr: { id: '' },
              visibility: { conditions: [] },
              button: true,
              link: { mode: 'external', url: '#' },
            },
          },
          { _id: 'e640c8c9-2047-8ad3-3311-ceeff314bb08', text: true, v: '-' },
          {
            _id: 'dbdb8996-1dfe-c7b5-c1a8-7c98b2addbc4',
            type: 'FormTextInput',
            tag: 'input',
            classes: ['b82519b8-8493-17d0-c1ee-0e3680a3271b'],
            children: [],
            data: {
              attr: {
                autofocus: false,
                maxlength: 256,
                name: 'Input-1',
                'data-name': 'Input-1',
                placeholder: '',
                type: 'number',
                id: 'Input-1',
                disabled: false,
                required: false,
              },
              xattr: [{ name: 'fs-inputcounter-element', value: 'input-1' }],
              form: { name: 'Input-1', type: 'input', passwordPage: false },
            },
          },
          {
            _id: 'f46768e3-5fcc-1f9b-307f-442500c99761',
            type: 'Link',
            tag: 'a',
            classes: ['b0934d9a-875a-bb42-0630-12090a77fbf1'],
            children: ['f46768e3-5fcc-1f9b-307f-442500c99762'],
            data: {
              search: { exclude: true },
              xattr: [{ name: 'fs-inputcounter-element', value: 'increment-1' }],
              block: '',
              displayName: '',
              devlink: { runtimeProps: {}, slot: '' },
              attr: { id: '' },
              visibility: { conditions: [] },
              button: true,
              link: { mode: 'external', url: '#' },
            },
          },
          { _id: 'f46768e3-5fcc-1f9b-307f-442500c99762', text: true, v: '+' },
          {
            _id: 'dbdb8996-1dfe-c7b5-c1a8-7c98b2addbc9',
            type: 'FormSuccessMessage',
            tag: 'div',
            classes: [],
            children: ['dbdb8996-1dfe-c7b5-c1a8-7c98b2addbca'],
            data: {
              form: { type: 'msg-done' },
              displayName: '',
              attr: { id: '' },
              xattr: [],
              search: { exclude: false },
              visibility: { conditions: [] },
            },
          },
          {
            _id: 'dbdb8996-1dfe-c7b5-c1a8-7c98b2addbca',
            type: 'Block',
            tag: 'div',
            classes: [],
            children: ['dbdb8996-1dfe-c7b5-c1a8-7c98b2addbcb'],
            data: {
              search: { exclude: false },
              xattr: [],
              text: true,
              displayName: '',
              devlink: { runtimeProps: {}, slot: '' },
              attr: { id: '' },
              visibility: { conditions: [] },
              tag: 'div',
            },
          },
          {
            _id: 'dbdb8996-1dfe-c7b5-c1a8-7c98b2addbcb',
            text: true,
            v: 'Thank you! Your submission has been received!',
          },
          {
            _id: 'dbdb8996-1dfe-c7b5-c1a8-7c98b2addbcc',
            type: 'FormErrorMessage',
            tag: 'div',
            classes: [],
            children: ['dbdb8996-1dfe-c7b5-c1a8-7c98b2addbcd'],
            data: {
              form: { type: 'msg-fail' },
              displayName: '',
              attr: { id: '' },
              xattr: [],
              search: { exclude: false },
              visibility: { conditions: [] },
            },
          },
          {
            _id: 'dbdb8996-1dfe-c7b5-c1a8-7c98b2addbcd',
            type: 'Block',
            tag: 'div',
            classes: [],
            children: ['dbdb8996-1dfe-c7b5-c1a8-7c98b2addbce'],
            data: {
              search: { exclude: false },
              xattr: [],
              text: true,
              displayName: '',
              devlink: { runtimeProps: {}, slot: '' },
              attr: { id: '' },
              visibility: { conditions: [] },
              tag: 'div',
            },
          },
          {
            _id: 'dbdb8996-1dfe-c7b5-c1a8-7c98b2addbce',
            text: true,
            v: 'Oops! Something went wrong while submitting the form.',
          },
        ],
        styles: [
          {
            _id: '15888a7f-7f99-6aba-31a8-940baa3eff35',
            fake: false,
            type: 'class',
            name: 'fs-inputcounter_form',
            namespace: '',
            comb: '',
            styleLess: 'display: flex; margin-bottom: 4rem; grid-column-gap: 1rem;',
            variants: {},
            children: [],
            createdBy: '5db95a67e381b2189edf0aba',
            selector: null,
          },
          {
            _id: 'b0934d9a-875a-bb42-0630-12090a77fbf1',
            fake: false,
            type: 'class',
            name: 'button',
            namespace: '',
            comb: '',
            styleLess:
              'position: relative; z-index: 1; padding-top: 0.75rem; padding-right: 1.25rem; padding-bottom: 0.75rem; padding-left: 1.25rem; justify-content: center; align-items: center; background-color: hsla(222, 82.57%, 57.25%, 1.00); transition-property: background-color; transition-duration: 200ms; transition-timing-function: ease; color: hsla(0, 0.00%, 100.00%, 1.00); font-weight: 600; text-align: center;',
            variants: {},
            children: [
              'b0934d9a-875a-bb42-0630-12090a77fcbf',
              '96240114-c262-72b3-90fb-46b0b97ab2de',
              '600a4817-ebbf-48df-ba87-e7e8b79eda1c',
              '8ce78756-2774-1ab6-6248-02680539765a',
            ],
            selector: null,
          },
          {
            _id: 'b82519b8-8493-17d0-c1ee-0e3680a3271b',
            fake: false,
            type: 'class',
            name: 'fs-inputcounter_input',
            namespace: '',
            comb: '',
            styleLess: 'width: 4rem; height: auto; margin-bottom: 0rem;',
            variants: {},
            children: [],
            createdBy: '5db95a67e381b2189edf0aba',
            selector: null,
          },
        ],
        assets: [],
        ix1: [],
        ix2: { interactions: [], events: [], actionLists: [] },
      },
      meta: {
        unlinkedSymbolCount: 0,
        droppedLinks: 0,
        dynBindRemovedCount: 0,
        dynListBindRemovedCount: 0,
        paginationRemovedCount: 0,
      },
    },
  },
  {
    title: 'Input Counter with a Clear Button',
    description: 'Increment and decrement (+ and -) counter in a Webflow Form.',
    data: {
      type: '@webflow/XscpData',
      payload: {
        nodes: [
          {
            _id: '05cc22f1-2147-553c-aac5-9687c7883a78',
            type: 'FormWrapper',
            tag: 'div',
            classes: [],
            children: [
              '05cc22f1-2147-553c-aac5-9687c7883a79',
              '05cc22f1-2147-553c-aac5-9687c7883a7f',
              '05cc22f1-2147-553c-aac5-9687c7883a82',
            ],
            data: {
              form: { type: 'wrapper' },
              displayName: '',
              attr: { id: '' },
              xattr: [],
              search: { exclude: true },
              visibility: { conditions: [] },
            },
          },
          {
            _id: '05cc22f1-2147-553c-aac5-9687c7883a79',
            type: 'FormForm',
            tag: 'form',
            classes: ['15888a7f-7f99-6aba-31a8-940baa3eff35'],
            children: [
              '05cc22f1-2147-553c-aac5-9687c7883a7a',
              '05cc22f1-2147-553c-aac5-9687c7883a7c',
              '05cc22f1-2147-553c-aac5-9687c7883a7d',
              '50a572ae-7ba0-b383-42a9-b403507c8213',
            ],
            data: {
              form: { type: 'form', name: 'Email Form' },
              search: { exclude: false },
              xattr: [],
              displayName: '',
              attr: {
                id: 'email-form',
                name: 'email-form',
                'data-name': 'Email Form',
                redirect: '',
                'data-redirect': '',
                action: '',
                method: 'get',
              },
              visibility: { conditions: [] },
              Source: { tag: 'Default form', val: {} },
            },
          },
          {
            _id: '05cc22f1-2147-553c-aac5-9687c7883a7a',
            type: 'Link',
            tag: 'a',
            classes: ['b0934d9a-875a-bb42-0630-12090a77fbf1'],
            children: ['05cc22f1-2147-553c-aac5-9687c7883a7b'],
            data: {
              search: { exclude: true },
              xattr: [{ name: 'fs-inputcounter-element', value: 'decrement-2' }],
              block: '',
              displayName: '',
              devlink: { runtimeProps: {}, slot: '' },
              attr: { id: '' },
              visibility: { conditions: [] },
              button: true,
              link: { mode: 'external', url: '#' },
            },
          },
          { _id: '05cc22f1-2147-553c-aac5-9687c7883a7b', text: true, v: '-' },
          {
            _id: '05cc22f1-2147-553c-aac5-9687c7883a7c',
            type: 'FormTextInput',
            tag: 'input',
            classes: ['b82519b8-8493-17d0-c1ee-0e3680a3271b'],
            children: [],
            data: {
              attr: {
                autofocus: false,
                maxlength: 256,
                name: 'Input-1',
                'data-name': 'Input-1',
                placeholder: '',
                type: 'number',
                id: 'Input-1',
                disabled: false,
                required: false,
              },
              xattr: [{ name: 'fs-inputcounter-element', value: 'input-2' }],
              form: { name: 'Input-1', type: 'input', passwordPage: false },
            },
          },
          {
            _id: '05cc22f1-2147-553c-aac5-9687c7883a7d',
            type: 'Link',
            tag: 'a',
            classes: ['b0934d9a-875a-bb42-0630-12090a77fbf1'],
            children: ['05cc22f1-2147-553c-aac5-9687c7883a7e'],
            data: {
              search: { exclude: true },
              xattr: [{ name: 'fs-inputcounter-element', value: 'increment-2' }],
              block: '',
              displayName: '',
              devlink: { runtimeProps: {}, slot: '' },
              attr: { id: '' },
              visibility: { conditions: [] },
              button: true,
              link: { mode: 'external', url: '#' },
            },
          },
          { _id: '05cc22f1-2147-553c-aac5-9687c7883a7e', text: true, v: '+' },
          {
            _id: '50a572ae-7ba0-b383-42a9-b403507c8213',
            type: 'Link',
            tag: 'a',
            classes: ['b0934d9a-875a-bb42-0630-12090a77fbf1'],
            children: ['50a572ae-7ba0-b383-42a9-b403507c8214'],
            data: {
              search: { exclude: true },
              xattr: [{ name: 'fs-inputcounter-element', value: 'clear-2' }],
              block: '',
              displayName: '',
              devlink: { runtimeProps: {}, slot: '' },
              attr: { id: '' },
              visibility: { conditions: [] },
              button: true,
              link: { mode: 'external', url: '#' },
            },
          },
          { _id: '50a572ae-7ba0-b383-42a9-b403507c8214', text: true, v: 'Clear' },
          {
            _id: '05cc22f1-2147-553c-aac5-9687c7883a7f',
            type: 'FormSuccessMessage',
            tag: 'div',
            classes: [],
            children: ['05cc22f1-2147-553c-aac5-9687c7883a80'],
            data: {
              form: { type: 'msg-done' },
              displayName: '',
              attr: { id: '' },
              xattr: [],
              search: { exclude: false },
              visibility: { conditions: [] },
            },
          },
          {
            _id: '05cc22f1-2147-553c-aac5-9687c7883a80',
            type: 'Block',
            tag: 'div',
            classes: [],
            children: ['05cc22f1-2147-553c-aac5-9687c7883a81'],
            data: {
              search: { exclude: false },
              xattr: [],
              text: true,
              displayName: '',
              devlink: { runtimeProps: {}, slot: '' },
              attr: { id: '' },
              visibility: { conditions: [] },
              tag: 'div',
            },
          },
          {
            _id: '05cc22f1-2147-553c-aac5-9687c7883a81',
            text: true,
            v: 'Thank you! Your submission has been received!',
          },
          {
            _id: '05cc22f1-2147-553c-aac5-9687c7883a82',
            type: 'FormErrorMessage',
            tag: 'div',
            classes: [],
            children: ['05cc22f1-2147-553c-aac5-9687c7883a83'],
            data: {
              form: { type: 'msg-fail' },
              displayName: '',
              attr: { id: '' },
              xattr: [],
              search: { exclude: false },
              visibility: { conditions: [] },
            },
          },
          {
            _id: '05cc22f1-2147-553c-aac5-9687c7883a83',
            type: 'Block',
            tag: 'div',
            classes: [],
            children: ['05cc22f1-2147-553c-aac5-9687c7883a84'],
            data: {
              search: { exclude: false },
              xattr: [],
              text: true,
              displayName: '',
              devlink: { runtimeProps: {}, slot: '' },
              attr: { id: '' },
              visibility: { conditions: [] },
              tag: 'div',
            },
          },
          {
            _id: '05cc22f1-2147-553c-aac5-9687c7883a84',
            text: true,
            v: 'Oops! Something went wrong while submitting the form.',
          },
        ],
        styles: [
          {
            _id: '15888a7f-7f99-6aba-31a8-940baa3eff35',
            fake: false,
            type: 'class',
            name: 'fs-inputcounter_form',
            namespace: '',
            comb: '',
            styleLess: 'display: flex; margin-bottom: 4rem; grid-column-gap: 1rem;',
            variants: {},
            children: [],
            createdBy: '5db95a67e381b2189edf0aba',
            selector: null,
          },
          {
            _id: 'b0934d9a-875a-bb42-0630-12090a77fbf1',
            fake: false,
            type: 'class',
            name: 'button',
            namespace: '',
            comb: '',
            styleLess:
              'position: relative; z-index: 1; padding-top: 0.75rem; padding-right: 1.25rem; padding-bottom: 0.75rem; padding-left: 1.25rem; justify-content: center; align-items: center; background-color: hsla(222, 82.57%, 57.25%, 1.00); transition-property: background-color; transition-duration: 200ms; transition-timing-function: ease; color: hsla(0, 0.00%, 100.00%, 1.00); font-weight: 600; text-align: center;',
            variants: {},
            children: [
              'b0934d9a-875a-bb42-0630-12090a77fcbf',
              '96240114-c262-72b3-90fb-46b0b97ab2de',
              '600a4817-ebbf-48df-ba87-e7e8b79eda1c',
              '8ce78756-2774-1ab6-6248-02680539765a',
            ],
            selector: null,
          },
          {
            _id: 'b82519b8-8493-17d0-c1ee-0e3680a3271b',
            fake: false,
            type: 'class',
            name: 'fs-inputcounter_input',
            namespace: '',
            comb: '',
            styleLess: 'width: 4rem; height: auto; margin-bottom: 0rem;',
            variants: {},
            children: [],
            createdBy: '5db95a67e381b2189edf0aba',
            selector: null,
          },
        ],
        assets: [],
        ix1: [],
        ix2: { interactions: [], events: [], actionLists: [] },
      },
      meta: {
        unlinkedSymbolCount: 0,
        droppedLinks: 0,
        dynBindRemovedCount: 0,
        dynListBindRemovedCount: 0,
        paginationRemovedCount: 0,
      },
    },
  },
  {
    title: 'Input Counter with a Clear Button and a Default Value',
    description: 'Increment and decrement (+ and -) counter in a Webflow Form.',
    data: {
      type: '@webflow/XscpData',
      payload: {
        nodes: [
          {
            _id: 'd255d48b-28b0-c5a8-6f05-0bb816087b02',
            type: 'FormWrapper',
            tag: 'div',
            classes: [],
            children: [
              'd255d48b-28b0-c5a8-6f05-0bb816087b03',
              'd255d48b-28b0-c5a8-6f05-0bb816087b09',
              'd255d48b-28b0-c5a8-6f05-0bb816087b0c',
            ],
            data: {
              form: { type: 'wrapper' },
              displayName: '',
              attr: { id: '' },
              xattr: [],
              search: { exclude: true },
              visibility: { conditions: [] },
            },
          },
          {
            _id: 'd255d48b-28b0-c5a8-6f05-0bb816087b03',
            type: 'FormForm',
            tag: 'form',
            classes: ['15888a7f-7f99-6aba-31a8-940baa3eff35'],
            children: [
              'd255d48b-28b0-c5a8-6f05-0bb816087b04',
              'd255d48b-28b0-c5a8-6f05-0bb816087b06',
              'd255d48b-28b0-c5a8-6f05-0bb816087b07',
              'c1657171-9bdb-1438-8fa3-fa7f7b0777e3',
            ],
            data: {
              form: { type: 'form', name: 'Email Form' },
              search: { exclude: false },
              xattr: [],
              displayName: '',
              attr: {
                id: 'email-form',
                name: 'email-form',
                'data-name': 'Email Form',
                redirect: '',
                'data-redirect': '',
                action: '',
                method: 'get',
              },
              visibility: { conditions: [] },
              Source: { tag: 'Default form', val: {} },
            },
          },
          {
            _id: 'd255d48b-28b0-c5a8-6f05-0bb816087b04',
            type: 'Link',
            tag: 'a',
            classes: ['b0934d9a-875a-bb42-0630-12090a77fbf1'],
            children: ['d255d48b-28b0-c5a8-6f05-0bb816087b05'],
            data: {
              search: { exclude: true },
              xattr: [{ name: 'fs-inputcounter-element', value: 'decrement-3' }],
              block: '',
              displayName: '',
              devlink: { runtimeProps: {}, slot: '' },
              attr: { id: '' },
              visibility: { conditions: [] },
              button: true,
              link: { mode: 'external', url: '#' },
            },
          },
          { _id: 'd255d48b-28b0-c5a8-6f05-0bb816087b05', text: true, v: '-' },
          {
            _id: 'd255d48b-28b0-c5a8-6f05-0bb816087b06',
            type: 'FormTextInput',
            tag: 'input',
            classes: ['b82519b8-8493-17d0-c1ee-0e3680a3271b'],
            children: [],
            data: {
              attr: {
                autofocus: false,
                maxlength: 256,
                name: 'Input-2',
                'data-name': 'Input-2',
                placeholder: '',
                type: 'number',
                id: 'Input-3',
                disabled: false,
                required: false,
              },
              xattr: [
                { name: 'fs-inputcounter-element', value: 'input-3' },
                { name: 'fs-inputcounter-initial', value: '10' },
              ],
              form: { name: 'Input-2', type: 'input', passwordPage: false },
            },
          },
          {
            _id: 'd255d48b-28b0-c5a8-6f05-0bb816087b07',
            type: 'Link',
            tag: 'a',
            classes: ['b0934d9a-875a-bb42-0630-12090a77fbf1'],
            children: ['d255d48b-28b0-c5a8-6f05-0bb816087b08'],
            data: {
              search: { exclude: true },
              xattr: [{ name: 'fs-inputcounter-element', value: 'increment-3' }],
              block: '',
              displayName: '',
              devlink: { runtimeProps: {}, slot: '' },
              attr: { id: '' },
              visibility: { conditions: [] },
              button: true,
              link: { mode: 'external', url: '#' },
            },
          },
          { _id: 'd255d48b-28b0-c5a8-6f05-0bb816087b08', text: true, v: '+' },
          {
            _id: 'c1657171-9bdb-1438-8fa3-fa7f7b0777e3',
            type: 'Link',
            tag: 'a',
            classes: ['b0934d9a-875a-bb42-0630-12090a77fbf1'],
            children: ['c1657171-9bdb-1438-8fa3-fa7f7b0777e4'],
            data: {
              search: { exclude: true },
              xattr: [{ name: 'fs-inputcounter-element', value: 'clear-3' }],
              block: '',
              displayName: '',
              devlink: { runtimeProps: {}, slot: '' },
              attr: { id: '' },
              visibility: { conditions: [] },
              button: true,
              link: { mode: 'external', url: '#' },
            },
          },
          { _id: 'c1657171-9bdb-1438-8fa3-fa7f7b0777e4', text: true, v: 'Clear' },
          {
            _id: 'd255d48b-28b0-c5a8-6f05-0bb816087b09',
            type: 'FormSuccessMessage',
            tag: 'div',
            classes: [],
            children: ['d255d48b-28b0-c5a8-6f05-0bb816087b0a'],
            data: {
              form: { type: 'msg-done' },
              displayName: '',
              attr: { id: '' },
              xattr: [],
              search: { exclude: false },
              visibility: { conditions: [] },
            },
          },
          {
            _id: 'd255d48b-28b0-c5a8-6f05-0bb816087b0a',
            type: 'Block',
            tag: 'div',
            classes: [],
            children: ['d255d48b-28b0-c5a8-6f05-0bb816087b0b'],
            data: {
              search: { exclude: false },
              xattr: [],
              text: true,
              displayName: '',
              devlink: { runtimeProps: {}, slot: '' },
              attr: { id: '' },
              visibility: { conditions: [] },
              tag: 'div',
            },
          },
          {
            _id: 'd255d48b-28b0-c5a8-6f05-0bb816087b0b',
            text: true,
            v: 'Thank you! Your submission has been received!',
          },
          {
            _id: 'd255d48b-28b0-c5a8-6f05-0bb816087b0c',
            type: 'FormErrorMessage',
            tag: 'div',
            classes: [],
            children: ['d255d48b-28b0-c5a8-6f05-0bb816087b0d'],
            data: {
              form: { type: 'msg-fail' },
              displayName: '',
              attr: { id: '' },
              xattr: [],
              search: { exclude: false },
              visibility: { conditions: [] },
            },
          },
          {
            _id: 'd255d48b-28b0-c5a8-6f05-0bb816087b0d',
            type: 'Block',
            tag: 'div',
            classes: [],
            children: ['d255d48b-28b0-c5a8-6f05-0bb816087b0e'],
            data: {
              search: { exclude: false },
              xattr: [],
              text: true,
              displayName: '',
              devlink: { runtimeProps: {}, slot: '' },
              attr: { id: '' },
              visibility: { conditions: [] },
              tag: 'div',
            },
          },
          {
            _id: 'd255d48b-28b0-c5a8-6f05-0bb816087b0e',
            text: true,
            v: 'Oops! Something went wrong while submitting the form.',
          },
        ],
        styles: [
          {
            _id: '15888a7f-7f99-6aba-31a8-940baa3eff35',
            fake: false,
            type: 'class',
            name: 'fs-inputcounter_form',
            namespace: '',
            comb: '',
            styleLess: 'display: flex; margin-bottom: 4rem; grid-column-gap: 1rem;',
            variants: {},
            children: [],
            createdBy: '5db95a67e381b2189edf0aba',
            selector: null,
          },
          {
            _id: 'b0934d9a-875a-bb42-0630-12090a77fbf1',
            fake: false,
            type: 'class',
            name: 'button',
            namespace: '',
            comb: '',
            styleLess:
              'position: relative; z-index: 1; padding-top: 0.75rem; padding-right: 1.25rem; padding-bottom: 0.75rem; padding-left: 1.25rem; justify-content: center; align-items: center; background-color: hsla(222, 82.57%, 57.25%, 1.00); transition-property: background-color; transition-duration: 200ms; transition-timing-function: ease; color: hsla(0, 0.00%, 100.00%, 1.00); font-weight: 600; text-align: center;',
            variants: {},
            children: [
              'b0934d9a-875a-bb42-0630-12090a77fcbf',
              '96240114-c262-72b3-90fb-46b0b97ab2de',
              '600a4817-ebbf-48df-ba87-e7e8b79eda1c',
              '8ce78756-2774-1ab6-6248-02680539765a',
            ],
            selector: null,
          },
          {
            _id: 'b82519b8-8493-17d0-c1ee-0e3680a3271b',
            fake: false,
            type: 'class',
            name: 'fs-inputcounter_input',
            namespace: '',
            comb: '',
            styleLess: 'width: 4rem; height: auto; margin-bottom: 0rem;',
            variants: {},
            children: [],
            createdBy: '5db95a67e381b2189edf0aba',
            selector: null,
          },
        ],
        assets: [],
        ix1: [],
        ix2: { interactions: [], events: [], actionLists: [] },
      },
      meta: {
        unlinkedSymbolCount: 0,
        droppedLinks: 0,
        dynBindRemovedCount: 0,
        dynListBindRemovedCount: 0,
        paginationRemovedCount: 0,
      },
    },
  },
  {
    title: 'Input Counter with a Clear Button and a Step, Min and Max.',
    description:
      'Increment and decrement (+ and -) counter in a Webflow Form. The native step, min and max HTML attributes are used for accessibility reasons.',
    data: {
      type: '@webflow/XscpData',
      payload: {
        nodes: [
          {
            _id: '41d285f6-4acd-4730-8f75-b3979ad433c3',
            type: 'FormWrapper',
            tag: 'div',
            classes: [],
            children: [
              '41d285f6-4acd-4730-8f75-b3979ad433c4',
              '41d285f6-4acd-4730-8f75-b3979ad433ca',
              '41d285f6-4acd-4730-8f75-b3979ad433cd',
            ],
            data: {
              form: { type: 'wrapper' },
              displayName: '',
              attr: { id: '' },
              xattr: [],
              search: { exclude: true },
              visibility: { conditions: [] },
            },
          },
          {
            _id: '41d285f6-4acd-4730-8f75-b3979ad433c4',
            type: 'FormForm',
            tag: 'form',
            classes: ['15888a7f-7f99-6aba-31a8-940baa3eff35'],
            children: [
              '41d285f6-4acd-4730-8f75-b3979ad433c5',
              '41d285f6-4acd-4730-8f75-b3979ad433c7',
              '41d285f6-4acd-4730-8f75-b3979ad433c8',
              '9cfd2ab3-1327-32a4-2129-9d13c2d42c51',
            ],
            data: {
              form: { type: 'form', name: 'Email Form' },
              search: { exclude: false },
              xattr: [],
              displayName: '',
              attr: {
                id: 'email-form',
                name: 'email-form',
                'data-name': 'Email Form',
                redirect: '',
                'data-redirect': '',
                action: '',
                method: 'get',
              },
              visibility: { conditions: [] },
              Source: { tag: 'Default form', val: {} },
            },
          },
          {
            _id: '41d285f6-4acd-4730-8f75-b3979ad433c5',
            type: 'Link',
            tag: 'a',
            classes: ['b0934d9a-875a-bb42-0630-12090a77fbf1'],
            children: ['41d285f6-4acd-4730-8f75-b3979ad433c6'],
            data: {
              search: { exclude: true },
              xattr: [
                { name: 'fs-inputcounter-element', value: 'decrement-4' },
                { name: 'data-testid', value: 'decrement' },
              ],
              block: '',
              displayName: '',
              devlink: { runtimeProps: {}, slot: '' },
              attr: { id: '' },
              visibility: { conditions: [] },
              button: true,
              link: { mode: 'external', url: '#' },
            },
          },
          { _id: '41d285f6-4acd-4730-8f75-b3979ad433c6', text: true, v: '-' },
          {
            _id: '41d285f6-4acd-4730-8f75-b3979ad433c7',
            type: 'FormTextInput',
            tag: 'input',
            classes: ['b82519b8-8493-17d0-c1ee-0e3680a3271b'],
            children: [],
            data: {
              attr: {
                autofocus: false,
                maxlength: 256,
                name: 'Input-3',
                'data-name': 'Input-3',
                placeholder: '',
                type: 'number',
                id: 'Input-4',
                disabled: false,
                required: false,
              },
              xattr: [
                { name: 'fs-inputcounter-element', value: 'input-4' },
                { name: 'fs-inputcounter-initial', value: '0.65' },
                { name: 'min', value: '0' },
                { name: 'max', value: '10' },
                { name: 'step', value: '0.5' },
                { name: 'data-testid', value: 'input' },
              ],
              form: { name: 'Input-3', type: 'input', passwordPage: false },
            },
          },
          {
            _id: '41d285f6-4acd-4730-8f75-b3979ad433c8',
            type: 'Link',
            tag: 'a',
            classes: ['b0934d9a-875a-bb42-0630-12090a77fbf1'],
            children: ['41d285f6-4acd-4730-8f75-b3979ad433c9'],
            data: {
              search: { exclude: true },
              xattr: [
                { name: 'fs-inputcounter-element', value: 'increment-4' },
                { name: 'data-testid', value: 'increment' },
              ],
              block: '',
              displayName: '',
              devlink: { runtimeProps: {}, slot: '' },
              attr: { id: '' },
              visibility: { conditions: [] },
              button: true,
              link: { mode: 'external', url: '#' },
            },
          },
          { _id: '41d285f6-4acd-4730-8f75-b3979ad433c9', text: true, v: '+' },
          {
            _id: '9cfd2ab3-1327-32a4-2129-9d13c2d42c51',
            type: 'Link',
            tag: 'a',
            classes: ['b0934d9a-875a-bb42-0630-12090a77fbf1'],
            children: ['9cfd2ab3-1327-32a4-2129-9d13c2d42c52'],
            data: {
              search: { exclude: true },
              xattr: [
                { name: 'fs-inputcounter-element', value: 'clear-4' },
                { name: 'data-testid', value: 'clear' },
              ],
              block: '',
              displayName: '',
              devlink: { runtimeProps: {}, slot: '' },
              attr: { id: '' },
              visibility: { conditions: [] },
              button: true,
              link: { mode: 'external', url: '#' },
            },
          },
          { _id: '9cfd2ab3-1327-32a4-2129-9d13c2d42c52', text: true, v: 'Clear' },
          {
            _id: '41d285f6-4acd-4730-8f75-b3979ad433ca',
            type: 'FormSuccessMessage',
            tag: 'div',
            classes: [],
            children: ['41d285f6-4acd-4730-8f75-b3979ad433cb'],
            data: {
              form: { type: 'msg-done' },
              displayName: '',
              attr: { id: '' },
              xattr: [],
              search: { exclude: false },
              visibility: { conditions: [] },
            },
          },
          {
            _id: '41d285f6-4acd-4730-8f75-b3979ad433cb',
            type: 'Block',
            tag: 'div',
            classes: [],
            children: ['41d285f6-4acd-4730-8f75-b3979ad433cc'],
            data: {
              search: { exclude: false },
              xattr: [],
              text: true,
              displayName: '',
              devlink: { runtimeProps: {}, slot: '' },
              attr: { id: '' },
              visibility: { conditions: [] },
              tag: 'div',
            },
          },
          {
            _id: '41d285f6-4acd-4730-8f75-b3979ad433cc',
            text: true,
            v: 'Thank you! Your submission has been received!',
          },
          {
            _id: '41d285f6-4acd-4730-8f75-b3979ad433cd',
            type: 'FormErrorMessage',
            tag: 'div',
            classes: [],
            children: ['41d285f6-4acd-4730-8f75-b3979ad433ce'],
            data: {
              form: { type: 'msg-fail' },
              displayName: '',
              attr: { id: '' },
              xattr: [],
              search: { exclude: false },
              visibility: { conditions: [] },
            },
          },
          {
            _id: '41d285f6-4acd-4730-8f75-b3979ad433ce',
            type: 'Block',
            tag: 'div',
            classes: [],
            children: ['41d285f6-4acd-4730-8f75-b3979ad433cf'],
            data: {
              search: { exclude: false },
              xattr: [],
              text: true,
              displayName: '',
              devlink: { runtimeProps: {}, slot: '' },
              attr: { id: '' },
              visibility: { conditions: [] },
              tag: 'div',
            },
          },
          {
            _id: '41d285f6-4acd-4730-8f75-b3979ad433cf',
            text: true,
            v: 'Oops! Something went wrong while submitting the form.',
          },
        ],
        styles: [
          {
            _id: '15888a7f-7f99-6aba-31a8-940baa3eff35',
            fake: false,
            type: 'class',
            name: 'fs-inputcounter_form',
            namespace: '',
            comb: '',
            styleLess: 'display: flex; margin-bottom: 4rem; grid-column-gap: 1rem;',
            variants: {},
            children: [],
            createdBy: '5db95a67e381b2189edf0aba',
            selector: null,
          },
          {
            _id: 'b0934d9a-875a-bb42-0630-12090a77fbf1',
            fake: false,
            type: 'class',
            name: 'button',
            namespace: '',
            comb: '',
            styleLess:
              'position: relative; z-index: 1; padding-top: 0.75rem; padding-right: 1.25rem; padding-bottom: 0.75rem; padding-left: 1.25rem; justify-content: center; align-items: center; background-color: hsla(222, 82.57%, 57.25%, 1.00); transition-property: background-color; transition-duration: 200ms; transition-timing-function: ease; color: hsla(0, 0.00%, 100.00%, 1.00); font-weight: 600; text-align: center;',
            variants: {},
            children: [
              'b0934d9a-875a-bb42-0630-12090a77fcbf',
              '96240114-c262-72b3-90fb-46b0b97ab2de',
              '600a4817-ebbf-48df-ba87-e7e8b79eda1c',
              '8ce78756-2774-1ab6-6248-02680539765a',
            ],
            selector: null,
          },
          {
            _id: 'b82519b8-8493-17d0-c1ee-0e3680a3271b',
            fake: false,
            type: 'class',
            name: 'fs-inputcounter_input',
            namespace: '',
            comb: '',
            styleLess: 'width: 4rem; height: auto; margin-bottom: 0rem;',
            variants: {},
            children: [],
            createdBy: '5db95a67e381b2189edf0aba',
            selector: null,
          },
        ],
        assets: [],
        ix1: [],
        ix2: { interactions: [], events: [], actionLists: [] },
      },
      meta: {
        unlinkedSymbolCount: 0,
        droppedLinks: 0,
        dynBindRemovedCount: 0,
        dynListBindRemovedCount: 0,
        paginationRemovedCount: 0,
      },
    },
  },
];

export default examples;
