import type { AttributeExamples } from '@finsweet/attributes-utils';

const examples: AttributeExamples = [
  {
    title: 'Basic Input Counter',
    description: 'Increment and decrement (+ and -) counter in a Webflow Form.',
    data: {
      type: '@webflow/XscpData',
      payload: {
        nodes: [
          {
            _id: '3a4e2289-6d9d-d5f2-d8d5-c59141df4696',
            type: 'FormWrapper',
            tag: 'div',
            classes: [],
            children: [
              '3a4e2289-6d9d-d5f2-d8d5-c59141df4697',
              '3a4e2289-6d9d-d5f2-d8d5-c59141df469f',
              '3a4e2289-6d9d-d5f2-d8d5-c59141df46a2',
            ],
            data: {
              form: { type: 'wrapper' },
              search: { exclude: true },
              displayName: '',
              attr: { id: '' },
              xattr: [],
              visibility: { conditions: [] },
            },
          },
          {
            _id: '3a4e2289-6d9d-d5f2-d8d5-c59141df4697',
            type: 'FormForm',
            tag: 'form',
            classes: [],
            children: ['7aa0a0ca-07f1-7dbc-e5a6-5604f6661acc'],
            data: {
              form: { type: 'form', name: 'Email Form' },
              search: { exclude: false },
              xattr: [],
              displayName: '',
              attr: {
                id: 'email-form',
                name: 'email-form',
                'data-name': 'Email Form',
                redirect: '',
                'data-redirect': '',
                action: '',
                method: 'get',
              },
              visibility: { conditions: [] },
              Source: { tag: 'Default form', val: {} },
            },
          },
          {
            _id: '7aa0a0ca-07f1-7dbc-e5a6-5604f6661acc',
            type: 'Block',
            tag: 'div',
            classes: ['b8644d33-09ce-5841-d9e6-b0e1908b5ef2'],
            children: ['7aa0a0ca-07f1-7dbc-e5a6-5604f6661acd', '7aa0a0ca-07f1-7dbc-e5a6-5604f6661ace'],
            data: {
              search: { exclude: false },
              xattr: [],
              text: false,
              displayName: '',
              devlink: { runtimeProps: {}, slot: '' },
              attr: { id: '' },
              visibility: { conditions: [] },
              tag: 'div',
            },
          },
          {
            _id: '7aa0a0ca-07f1-7dbc-e5a6-5604f6661acd',
            type: 'HtmlEmbed',
            tag: 'div',
            classes: ['b8644d33-09ce-5841-d9e6-b0e1908b5ef3'],
            children: [],
            v: '<!-- [Finsweet Attributes] Input Counter -->\n<script>(()=>{var t="https://cdn.jsdelivr.net/npm/@finsweet/attributes-inputcounter@1/inputcounter.js",e=document.querySelector(`script[src="${t}"]`);e||(e=document.createElement("script"),e.async=!0,e.src=t,document.head.append(e));})();</script>',
            data: {
              insideRTE: false,
              search: { exclude: true },
              embed: {
                type: 'html',
                meta: {
                  html: '<!-- [Finsweet Attributes] Input Counter -->\n<script>(()=>{var t="https://cdn.jsdelivr.net/npm/@finsweet/attributes-inputcounter@1/inputcounter.js",e=document.querySelector(`script[src="${t}"]`);e||(e=document.createElement("script"),e.async=!0,e.src=t,document.head.append(e));})();</script>',
                  div: false,
                  iframe: false,
                  script: true,
                  compilable: false,
                },
              },
            },
          },
          {
            _id: '7aa0a0ca-07f1-7dbc-e5a6-5604f6661ace',
            type: 'Block',
            tag: 'div',
            classes: ['b8644d33-09ce-5841-d9e6-b0e1908b5ef4'],
            children: [
              '7aa0a0ca-07f1-7dbc-e5a6-5604f6661acf',
              '7aa0a0ca-07f1-7dbc-e5a6-5604f6661ad0',
              '7aa0a0ca-07f1-7dbc-e5a6-5604f6661ad3',
            ],
            data: {
              search: { exclude: false },
              xattr: [],
              text: false,
              displayName: '',
              devlink: { runtimeProps: {}, slot: '' },
              attr: { id: '' },
              visibility: { conditions: [] },
              tag: 'div',
            },
          },
          {
            _id: '7aa0a0ca-07f1-7dbc-e5a6-5604f6661acf',
            type: 'FormTextInput',
            tag: 'input',
            classes: ['b8644d33-09ce-5841-d9e6-b0e1908b5ef5'],
            children: [],
            data: {
              attr: {
                autofocus: false,
                maxlength: 256,
                name: 'Counter',
                'data-name': 'Counter',
                placeholder: '',
                type: 'text',
                id: 'fs-inputcounter-1-input',
                disabled: false,
                required: true,
              },
              xattr: [{ name: 'fs-inputcounter-element', value: 'input' }],
              form: { name: 'Counter', type: 'input', passwordPage: false },
            },
          },
          {
            _id: '7aa0a0ca-07f1-7dbc-e5a6-5604f6661ad0',
            type: 'Block',
            tag: 'div',
            classes: ['b8644d33-09ce-5841-d9e6-b0e1908b5ef6'],
            children: ['7aa0a0ca-07f1-7dbc-e5a6-5604f6661ad1'],
            data: {
              search: { exclude: false },
              xattr: [
                { name: 'fs-inputcounter-element', value: 'decrement' },
                { name: 'role', value: 'button' },
                { name: 'aria-label', value: 'Decrement input value' },
                { name: 'tabindex', value: '0' },
                { name: 'aria-controls', value: 'fs-inputcounter-1-input' },
              ],
              text: false,
              displayName: '',
              devlink: { runtimeProps: {}, slot: '' },
              attr: { id: '' },
              visibility: { conditions: [] },
              tag: 'div',
            },
          },
          {
            _id: '7aa0a0ca-07f1-7dbc-e5a6-5604f6661ad1',
            type: 'Block',
            tag: 'div',
            classes: [],
            children: ['7aa0a0ca-07f1-7dbc-e5a6-5604f6661ad2'],
            data: {
              search: { exclude: false },
              xattr: [],
              text: true,
              displayName: '',
              devlink: { runtimeProps: {}, slot: '' },
              attr: { id: '' },
              visibility: { conditions: [] },
              tag: 'div',
            },
          },
          { _id: '7aa0a0ca-07f1-7dbc-e5a6-5604f6661ad2', text: true, v: '-' },
          {
            _id: '7aa0a0ca-07f1-7dbc-e5a6-5604f6661ad3',
            type: 'Block',
            tag: 'div',
            classes: ['b8644d33-09ce-5841-d9e6-b0e1908b5ef6'],
            children: ['7aa0a0ca-07f1-7dbc-e5a6-5604f6661ad4'],
            data: {
              search: { exclude: false },
              xattr: [
                { name: 'fs-inputcounter-element', value: 'increment' },
                { name: 'role', value: 'button' },
                { name: 'aria-label', value: 'Increment input value' },
                { name: 'tabindex', value: '0' },
                { name: 'aria-controls', value: 'fs-inputcounter-1-input' },
              ],
              text: false,
              displayName: '',
              devlink: { runtimeProps: {}, slot: '' },
              attr: { id: '' },
              visibility: { conditions: [] },
              tag: 'div',
            },
          },
          {
            _id: '7aa0a0ca-07f1-7dbc-e5a6-5604f6661ad4',
            type: 'Block',
            tag: 'div',
            classes: [],
            children: ['7aa0a0ca-07f1-7dbc-e5a6-5604f6661ad5'],
            data: {
              search: { exclude: false },
              xattr: [],
              text: true,
              displayName: '',
              devlink: { runtimeProps: {}, slot: '' },
              attr: { id: '' },
              visibility: { conditions: [] },
              tag: 'div',
            },
          },
          { _id: '7aa0a0ca-07f1-7dbc-e5a6-5604f6661ad5', text: true, v: '+' },
          {
            _id: '3a4e2289-6d9d-d5f2-d8d5-c59141df469f',
            type: 'FormSuccessMessage',
            tag: 'div',
            classes: [],
            children: ['3a4e2289-6d9d-d5f2-d8d5-c59141df46a0'],
            data: {
              form: { type: 'msg-done' },
              displayName: '',
              attr: { id: '' },
              xattr: [],
              search: { exclude: false },
              visibility: { conditions: [] },
            },
          },
          {
            _id: '3a4e2289-6d9d-d5f2-d8d5-c59141df46a0',
            type: 'Block',
            tag: 'div',
            classes: [],
            children: ['3a4e2289-6d9d-d5f2-d8d5-c59141df46a1'],
            data: {
              search: { exclude: false },
              xattr: [],
              text: true,
              displayName: '',
              devlink: { runtimeProps: {}, slot: '' },
              attr: { id: '' },
              visibility: { conditions: [] },
              tag: 'div',
            },
          },
          {
            _id: '3a4e2289-6d9d-d5f2-d8d5-c59141df46a1',
            text: true,
            v: 'Thank you! Your submission has been received!',
          },
          {
            _id: '3a4e2289-6d9d-d5f2-d8d5-c59141df46a2',
            type: 'FormErrorMessage',
            tag: 'div',
            classes: [],
            children: ['3a4e2289-6d9d-d5f2-d8d5-c59141df46a3'],
            data: {
              form: { type: 'msg-fail' },
              displayName: '',
              attr: { id: '' },
              xattr: [],
              search: { exclude: false },
              visibility: { conditions: [] },
            },
          },
          {
            _id: '3a4e2289-6d9d-d5f2-d8d5-c59141df46a3',
            type: 'Block',
            tag: 'div',
            classes: [],
            children: ['3a4e2289-6d9d-d5f2-d8d5-c59141df46a4'],
            data: {
              search: { exclude: false },
              xattr: [],
              text: true,
              displayName: '',
              devlink: { runtimeProps: {}, slot: '' },
              attr: { id: '' },
              visibility: { conditions: [] },
              tag: 'div',
            },
          },
          {
            _id: '3a4e2289-6d9d-d5f2-d8d5-c59141df46a4',
            text: true,
            v: 'Oops! Something went wrong while submitting the form.',
          },
        ],
        styles: [
          {
            _id: 'b8644d33-09ce-5841-d9e6-b0e1908b5ef2',
            fake: false,
            type: 'class',
            name: 'fs_inputcounter-1_component',
            namespace: '',
            comb: '',
            styleLess:
              'display: grid; grid-auto-columns: 1fr; grid-column-gap: 1rem; grid-row-gap: 1rem; grid-template-columns: 1fr; grid-template-rows: auto;',
            variants: {},
            children: [],
            createdBy: '54441c96b0981db6504faf03',
            selector: null,
          },
          {
            _id: 'b8644d33-09ce-5841-d9e6-b0e1908b5ef3',
            fake: false,
            type: 'class',
            name: 'fs_inputcounter-1_embed',
            namespace: '',
            comb: '',
            styleLess: '',
            variants: {},
            children: [],
            createdBy: '54441c96b0981db6504faf03',
            selector: null,
          },
          {
            _id: 'b8644d33-09ce-5841-d9e6-b0e1908b5ef4',
            fake: false,
            type: 'class',
            name: 'fs_inputcounter-1_wrapper',
            namespace: '',
            comb: '',
            styleLess:
              'display: grid; justify-content: start; justify-items: start; grid-auto-flow: column; grid-auto-columns: auto; grid-column-gap: 1rem; grid-row-gap: 1rem; grid-template-columns: auto; grid-template-rows: auto;',
            variants: {},
            children: [],
            createdBy: '54441c96b0981db6504faf03',
            selector: null,
          },
          {
            _id: 'b8644d33-09ce-5841-d9e6-b0e1908b5ef5',
            fake: false,
            type: 'class',
            name: 'fs_inputcounter-1_input',
            namespace: '',
            comb: '',
            styleLess:
              'min-height: 3rem; margin-bottom: 0px; border-top-style: none; border-top-width: 1px; border-top-color: black; border-right-style: none; border-right-width: 1px; border-right-color: black; border-bottom-style: none; border-bottom-width: 1px; border-bottom-color: black; border-left-style: none; border-left-width: 1px; border-left-color: black; font-size: 1rem; text-align: center;',
            variants: {},
            children: [],
            createdBy: '54441c96b0981db6504faf03',
            selector: null,
          },
          {
            _id: 'b8644d33-09ce-5841-d9e6-b0e1908b5ef6',
            fake: false,
            type: 'class',
            name: 'fs_inputcounter-1_button',
            namespace: '',
            comb: '',
            styleLess:
              'display: flex; width: 3rem; height: 3rem; flex-direction: row; justify-content: center; align-items: center; background-color: hsla(208.10526315789474, 83.33%, 44.71%, 1.00); color: hsla(0, 0.00%, 100.00%, 1.00); font-size: 1.5rem; cursor: pointer;',
            variants: {
              'main_focus-visible': {
                styleLess: 'outline-color: #9b9b9b; outline-offset: 4px; outline-style: solid; outline-width: 2px;',
              },
            },
            children: [],
            createdBy: '54441c96b0981db6504faf03',
            selector: null,
          },
        ],
        assets: [],
        ix1: [],
        ix2: { interactions: [], events: [], actionLists: [] },
      },
      meta: {
        unlinkedSymbolCount: 0,
        droppedLinks: 0,
        dynBindRemovedCount: 0,
        dynListBindRemovedCount: 0,
        paginationRemovedCount: 0,
      },
    },
  },
];

export default examples;
