import type { AttributeExamples } from '$global/types/examples';

const examples: AttributeExamples = [
  {
    title: 'Combobox',
    description: 'Select an item from a large list of options by searching using an input field.',
    data: {
      type: '@webflow/XscpData',
      payload: {
        nodes: [
          {
            _id: '4397c877-7b78-83c3-b6aa-758cc9066071',
            type: 'DropdownWrapper',
            tag: 'div',
            classes: ['50b14e7d-64a9-3bcf-1bd7-a1122a7cae75'],
            children: ['4397c877-7b78-83c3-b6aa-758cc9066072', '4397c877-7b78-83c3-b6aa-758cc9066076'],
            data: {
              search: { exclude: true },
              xattr: [{ name: 'fs-combobox-element', value: 'dropdown' }],
              displayName: '',
              dropdown: { type: 'wrapper' },
              attr: { 'data-hover': false, 'data-delay': 0, id: '' },
              visibility: { conditions: [] },
              tag: 'div',
            },
          },
          {
            _id: '4397c877-7b78-83c3-b6aa-758cc9066072',
            type: 'DropdownToggle',
            tag: 'div',
            classes: ['36f33af5-a447-9d4c-82dd-87f58cec3b18'],
            children: [
              'c73dd626-b665-4d54-11dd-fe59698efa9a',
              '8f230aa0-b105-582b-039f-618296416b81',
              '94bdd710-5adc-6a1d-a057-1aae2f2d355b',
              'dd2bb2ce-fbb3-ff24-53b8-8afa495ce848',
            ],
            data: {
              search: { exclude: false },
              xattr: [],
              displayName: '',
              dropdown: { type: 'toggle' },
              attr: { id: '' },
              visibility: { conditions: [] },
              tag: 'div',
            },
          },
          {
            _id: 'c73dd626-b665-4d54-11dd-fe59698efa9a',
            type: 'FormSelect',
            tag: 'select',
            classes: ['c9374ae8-bd12-171b-864d-944b2ca19824'],
            children: [],
            data: {
              attr: { id: 'field-3', name: 'field-3', 'data-name': 'Field 3', required: false, multiple: false },
              form: {
                type: 'select',
                opts: [
                  { t: 'Select one...', v: '' },
                  { t: 'Arsenal', v: 'arsenal' },
                  { t: 'Liverpool', v: 'liverpool' },
                  { t: 'Barcelona', v: 'barcelona' },
                  { t: 'Sevilla', v: 'sevilla' },
                  { t: 'Brentford', v: 'brentford' },
                  { t: 'Zenit', v: 'zenit' },
                  { t: 'Juventus', v: 'juventus' },
                  { t: 'Napoli', v: 'napoli' },
                  { t: 'PSG', v: 'psg' },
                  { t: 'Marseille', v: 'marseille' },
                  { t: 'Monaco', v: 'monaco' },
                  { t: 'Lille', v: 'lille' },
                  { t: 'Nantes', v: 'nantes' },
                  { t: 'Rangers', v: 'rangers' },
                  { t: 'Porto', v: 'porto' },
                  { t: 'Benfica', v: 'benfica' },
                  { t: 'Olympiacos', v: 'olympiacos' },
                  { t: 'Ajax', v: 'ajax' },
                  { t: 'Lazio', v: 'lazio' },
                  { t: 'Freiburg', v: 'freiburg' },
                  { t: 'Atalanta', v: 'atalanta' },
                  { t: 'Sporting', v: 'sporting' },
                  { t: 'Udinese', v: 'udinese' },
                ],
                name: 'Field 3',
              },
            },
          },
          {
            _id: '8f230aa0-b105-582b-039f-618296416b81',
            type: 'FormTextInput',
            tag: 'input',
            classes: ['9d228982-a720-9c73-144d-a6d2df1b0f4e'],
            children: [],
            data: {
              attr: {
                autofocus: false,
                maxlength: 256,
                name: 'field-2',
                'data-name': 'Field 2',
                placeholder: '',
                type: 'text',
                id: 'field-2',
                disabled: false,
                required: true,
              },
              form: { type: 'input', name: 'Field 2', passwordPage: false },
              visibility: { conditions: [true] },
            },
          },
          {
            _id: '94bdd710-5adc-6a1d-a057-1aae2f2d355b',
            type: 'HtmlEmbed',
            tag: 'div',
            classes: ['ce0f9090-4a58-3b19-cd06-cfe0ccbc04d9'],
            children: [],
            v: '<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">\n  <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />\n</svg>',
            data: {
              insideRTE: false,
              search: { exclude: true },
              xattr: [
                { name: 'fs-combobox-element', value: 'option-reset' },
                { name: 'tabindex', value: '0' },
                { name: 'role', value: 'button' },
              ],
              embed: {
                type: 'html',
                meta: {
                  html: '<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">\n  <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />\n</svg>',
                  div: false,
                  iframe: false,
                  script: false,
                  compilable: false,
                },
              },
            },
          },
          {
            _id: 'dd2bb2ce-fbb3-ff24-53b8-8afa495ce848',
            type: 'HtmlEmbed',
            tag: 'div',
            classes: ['4613224e-dc00-b5f3-6b83-fb62aa6569fd'],
            children: [],
            v: '<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">\n  <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 8.25l-7.5 7.5-7.5-7.5" />\n</svg>',
            data: {
              insideRTE: false,
              search: { exclude: true },
              embed: {
                type: 'html',
                meta: {
                  html: '<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">\n  <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 8.25l-7.5 7.5-7.5-7.5" />\n</svg>',
                  div: false,
                  iframe: false,
                  script: false,
                  compilable: false,
                },
              },
            },
          },
          {
            _id: '4397c877-7b78-83c3-b6aa-758cc9066076',
            type: 'DropdownList',
            tag: 'nav',
            classes: ['4bd5ad3a-790c-348d-e004-c10b00a3950d'],
            children: ['912e7081-f717-d195-ae73-161d206e1649', 'ddd70407-1fbc-f15b-28b3-3c01e8cf749e'],
            data: {
              search: { exclude: false },
              xattr: [],
              displayName: '',
              dropdown: { type: 'list' },
              attr: { id: '' },
              visibility: { conditions: [] },
              tag: 'nav',
            },
          },
          {
            _id: '912e7081-f717-d195-ae73-161d206e1649',
            type: 'Block',
            tag: 'div',
            classes: ['886cf8e3-2d47-f26b-032e-08e429575688'],
            children: ['72b34cb5-dbc6-0a0f-d188-c279c1005dd9'],
            data: {
              search: { exclude: false },
              xattr: [{ name: 'fs-combobox-element', value: 'empty' }],
              text: true,
              displayName: '',
              devlink: { runtimeProps: {}, slot: '' },
              attr: { id: '' },
              visibility: { conditions: [] },
              tag: 'div',
            },
          },
          { _id: '72b34cb5-dbc6-0a0f-d188-c279c1005dd9', text: true, v: 'No results found' },
          {
            _id: 'ddd70407-1fbc-f15b-28b3-3c01e8cf749e',
            type: 'Link',
            tag: 'a',
            classes: ['dfe9eabe-52cf-675c-66d3-fa5d2a362986'],
            children: ['6213eb4f-7a41-5a6a-8c88-a63ef15e2978', 'ddd70407-1fbc-f15b-28b3-3c01e8cf74a0'],
            data: {
              search: { exclude: false },
              xattr: [],
              block: 'inline',
              displayName: '',
              devlink: { runtimeProps: {}, slot: '' },
              attr: { id: '', href: '#' },
              visibility: { conditions: [] },
              button: false,
              link: { mode: 'external' },
            },
          },
          {
            _id: '6213eb4f-7a41-5a6a-8c88-a63ef15e2978',
            type: 'HtmlEmbed',
            tag: 'div',
            classes: ['bf516ee7-1e3c-54e9-cb7d-17ec5dfbd888'],
            children: [],
            v: '<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">\n  <path stroke-linecap="round" stroke-linejoin="round" d="M17.25 8.25L21 12m0 0l-3.75 3.75M21 12H3" />\n</svg>',
            data: {
              insideRTE: false,
              search: { exclude: true },
              embed: {
                type: 'html',
                meta: {
                  html: '<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">\n  <path stroke-linecap="round" stroke-linejoin="round" d="M17.25 8.25L21 12m0 0l-3.75 3.75M21 12H3" />\n</svg>',
                  div: false,
                  iframe: false,
                  script: false,
                  compilable: false,
                },
              },
            },
          },
          {
            _id: 'ddd70407-1fbc-f15b-28b3-3c01e8cf74a0',
            type: 'Block',
            tag: 'div',
            classes: [],
            children: ['674dea5f-3153-f306-f10a-a1f6ffd43a2f'],
            data: {
              search: { exclude: false },
              xattr: [{ name: 'fs-combobox-element', value: 'label' }],
              text: true,
              displayName: '',
              devlink: { runtimeProps: {}, slot: '' },
              attr: { id: '' },
              visibility: { conditions: [] },
              tag: 'div',
            },
          },
          { _id: '674dea5f-3153-f306-f10a-a1f6ffd43a2f', text: true, v: 'Option Value' },
        ],
        styles: [
          {
            _id: 'dfe9eabe-52cf-675c-66d3-fa5d2a362986',
            fake: false,
            type: 'class',
            name: 'fs-selectcustom_option',
            namespace: '',
            comb: '',
            styleLess:
              'display: flex; padding-top: 0.375rem; padding-right: 1rem; padding-bottom: 0.375rem; padding-left: 1rem; align-items: center; border-bottom-style: solid; border-bottom-width: 1px; border-bottom-color: hsla(0, 0.00%, 0.00%, 0.20); background-color: transparent; text-decoration: none;',
            variants: {
              main_hover: {
                styleLess:
                  'outline-color: hsla(222, 82.57%, 57.25%, 1.00); outline-offset: -0.125rem; outline-style: solid; outline-width: 0.125rem;',
              },
              main_current: {
                styleLess: 'background-color: hsla(222, 82.57%, 57.25%, 1.00); color: hsla(222, 0.00%, 100.00%, 1.00);',
              },
              main_focus: {
                styleLess:
                  'outline-color: hsla(222, 82.57%, 57.25%, 1.00); outline-offset: -0.125rem; outline-style: solid; outline-width: 0.125rem;',
              },
            },
            children: [],
            selector: null,
          },
          {
            _id: 'ce0f9090-4a58-3b19-cd06-cfe0ccbc04d9',
            fake: false,
            type: 'class',
            name: 'fs-combobox_clear',
            namespace: '',
            comb: '',
            styleLess:
              'position: absolute; left: auto; top: 0%; right: 2.375rem; bottom: 0%; display: flex; width: 2.375rem; padding-top: 0.5rem; padding-right: 0.5rem; padding-bottom: 0.5rem; padding-left: 0.5rem; flex-direction: column; justify-content: center; cursor: pointer;',
            variants: {},
            children: ['cd7f6a08-cd10-3ddd-ba61-2479bdd7512a'],
            createdBy: '5db95a67e381b2189edf0aba',
            selector: null,
          },
          {
            _id: 'bf516ee7-1e3c-54e9-cb7d-17ec5dfbd888',
            fake: false,
            type: 'class',
            name: 'fs-combobox_icon',
            namespace: '',
            comb: '',
            styleLess: 'display: flex; width: 1rem; margin-right: 0.5rem; flex-direction: column;',
            variants: {},
            children: [],
            createdBy: '5db95a67e381b2189edf0aba',
            selector: null,
          },
          {
            _id: '36f33af5-a447-9d4c-82dd-87f58cec3b18',
            fake: false,
            type: 'class',
            name: 'fs-combobox_dropdown-toggle',
            namespace: '',
            comb: '',
            styleLess:
              'display: flex; padding-top: 0rem; padding-right: 0rem; padding-bottom: 0rem; padding-left: 0rem; border-top-style: solid; border-top-width: 1px; border-top-color: hsla(0, 0.00%, 0.00%, 1.00); border-right-style: solid; border-right-width: 1px; border-right-color: hsla(0, 0.00%, 0.00%, 1.00); border-bottom-style: solid; border-bottom-width: 1px; border-bottom-color: hsla(0, 0.00%, 0.00%, 1.00); border-left-style: solid; border-left-width: 1px; border-left-color: hsla(0, 0.00%, 0.00%, 1.00);',
            variants: {
              main_focus: {
                styleLess:
                  'border-top-color: #1976d2; border-right-color: #1976d2; border-bottom-color: #1976d2; border-left-color: #1976d2;',
              },
            },
            children: [],
            createdBy: '5db95a67e381b2189edf0aba',
            selector: null,
          },
          {
            _id: '4613224e-dc00-b5f3-6b83-fb62aa6569fd',
            fake: false,
            type: 'class',
            name: 'fs-combobox_arrow',
            namespace: '',
            comb: '',
            styleLess:
              'position: absolute; left: auto; top: 0%; right: 0%; bottom: 0%; display: flex; width: 2.375rem; padding-top: 0.5rem; padding-right: 0.5rem; padding-bottom: 0.5rem; padding-left: 0.5rem; flex-direction: column; justify-content: center;',
            variants: {},
            children: [],
            createdBy: '5db95a67e381b2189edf0aba',
            selector: null,
          },
          {
            _id: '4bd5ad3a-790c-348d-e004-c10b00a3950d',
            fake: false,
            type: 'class',
            name: 'fs-combobox_list',
            namespace: '',
            comb: '',
            styleLess: '',
            variants: {
              main_open: {
                styleLess:
                  'overflow: auto; max-height: 20rem; border-top-style: solid; border-top-width: 1px; border-top-color: black; border-right-style: solid; border-right-width: 1px; border-right-color: black; border-bottom-style: solid; border-bottom-width: 1px; border-bottom-color: black; border-left-style: solid; border-left-width: 1px; border-left-color: black; background-color: hsla(0, 0.00%, 100.00%, 1.00);',
              },
            },
            children: [],
            createdBy: '5db95a67e381b2189edf0aba',
            selector: null,
          },
          {
            _id: '886cf8e3-2d47-f26b-032e-08e429575688',
            fake: false,
            type: 'class',
            name: 'fs-combobox_empty',
            namespace: '',
            comb: '',
            styleLess: 'padding-top: 0.5rem; padding-right: 0.5rem; padding-bottom: 0.5rem; padding-left: 0.5rem;',
            variants: {},
            children: [],
            createdBy: '5db95a67e381b2189edf0aba',
            selector: null,
          },
          {
            _id: '9d228982-a720-9c73-144d-a6d2df1b0f4e',
            fake: false,
            type: 'class',
            name: 'fs-combobox_input',
            namespace: '',
            comb: '',
            styleLess:
              'width: 20rem; margin-bottom: 0rem; border-top-style: none; border-top-width: 1px; border-top-color: black; border-right-style: none; border-right-width: 1px; border-right-color: black; border-bottom-style: none; border-bottom-width: 1px; border-bottom-color: black; border-left-style: none; border-left-width: 1px; border-left-color: black;',
            variants: {
              main_focus: {
                styleLess:
                  'outline-color: hsla(222, 82.57%, 57.25%, 1.00); outline-style: solid; outline-width: 0.125rem;',
              },
              'main_focus-visible': {
                styleLess:
                  'outline-color: hsla(222, 82.57%, 57.25%, 1.00); outline-offset: 0px; outline-style: solid; outline-width: 0.125rem;',
              },
            },
            children: [],
            createdBy: '5db95a67e381b2189edf0aba',
            selector: null,
          },
          {
            _id: '50b14e7d-64a9-3bcf-1bd7-a1122a7cae75',
            fake: false,
            type: 'class',
            name: 'fs-combobox_dropdown',
            namespace: '',
            comb: '',
            styleLess: '',
            variants: {},
            children: [],
            createdBy: '5db95a67e381b2189edf0aba',
            selector: null,
          },
          {
            _id: 'c9374ae8-bd12-171b-864d-944b2ca19824',
            fake: false,
            type: 'class',
            name: 'fs-combobox_select',
            namespace: '',
            comb: '',
            styleLess: 'display: none;',
            variants: {},
            children: [],
            createdBy: '5db95a67e381b2189edf0aba',
            selector: null,
          },
        ],
        assets: [],
        ix1: [],
        ix2: { interactions: [], events: [], actionLists: [] },
      },
      meta: {
        unlinkedSymbolCount: 0,
        droppedLinks: 1,
        dynBindRemovedCount: 0,
        dynListBindRemovedCount: 0,
        paginationRemovedCount: 0,
      },
    },
  },
];

export default examples;
