import type { AttributeExamples } from '@finsweet/attributes-utils';

const examples: AttributeExamples = [
  {
    title: 'Combobox',
    description: 'Select an item from a large list of options by searching using an input field.',
    data: {
      type: '@webflow/XscpData',
      payload: {
        nodes: [
          {
            _id: '51f9269f-da1b-9749-0950-12d0a2c7e150',
            type: 'DropdownWrapper',
            tag: 'div',
            classes: ['1f84ad3a-62cb-466f-570c-99c02ba6b104'],
            children: ['51f9269f-da1b-9749-0950-12d0a2c7e151', '51f9269f-da1b-9749-0950-12d0a2c7e156'],
            data: {
              search: { exclude: true },
              xattr: [{ name: 'fs-combobox-element', value: 'dropdown' }],
              displayName: '',
              dropdown: { type: 'wrapper' },
              attr: { 'data-hover': false, 'data-delay': 0, id: '' },
              visibility: { conditions: [] },
              tag: 'div',
            },
          },
          {
            _id: '51f9269f-da1b-9749-0950-12d0a2c7e151',
            type: 'DropdownToggle',
            tag: 'div',
            classes: ['973a8a90-8d72-c3ed-1af9-319dccecd7d5'],
            children: [
              '51f9269f-da1b-9749-0950-12d0a2c7e153',
              '51f9269f-da1b-9749-0950-12d0a2c7e154',
              '51f9269f-da1b-9749-0950-12d0a2c7e155',
            ],
            data: {
              search: { exclude: false },
              xattr: [],
              displayName: '',
              dropdown: { type: 'toggle' },
              attr: { id: '' },
              visibility: { conditions: [] },
              tag: 'div',
            },
          },
          {
            _id: '51f9269f-da1b-9749-0950-12d0a2c7e153',
            type: 'FormTextInput',
            tag: 'input',
            classes: ['e56c6b90-c01a-6eb8-8dbc-7a38442d1942'],
            children: [],
            data: {
              attr: {
                autofocus: false,
                maxlength: 256,
                name: 'Text-Input',
                'data-name': 'Text Input',
                placeholder: '',
                type: 'text',
                id: 'Text-Input',
                disabled: false,
                required: true,
              },
              xattr: [{ name: 'fs-combobox-element', value: 'text-input' }],
              form: { name: 'Text Input', type: 'input', passwordPage: false },
            },
          },
          {
            _id: '51f9269f-da1b-9749-0950-12d0a2c7e154',
            type: 'HtmlEmbed',
            tag: 'div',
            classes: ['6109b72c-aefe-a83a-143a-40f7277eaec9'],
            children: [],
            v: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" width="100%" height="100%" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><path fill="currentColor" d="M19 6.41L17.59 5L12 10.59L6.41 5L5 6.41L10.59 12L5 17.59L6.41 19L12 13.41L17.59 19L19 17.59L13.41 12L19 6.41z"></path></svg>',
            data: {
              insideRTE: false,
              search: { exclude: true },
              xattr: [
                { name: 'fs-combobox-element', value: 'clear' },
                { name: 'tabindex', value: '0' },
                { name: 'role', value: 'button' },
              ],
              embed: {
                type: 'html',
                meta: {
                  html: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" width="100%" height="100%" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><path fill="currentColor" d="M19 6.41L17.59 5L12 10.59L6.41 5L5 6.41L10.59 12L5 17.59L6.41 19L12 13.41L17.59 19L19 17.59L13.41 12L19 6.41z"></path></svg>',
                  div: false,
                  iframe: false,
                  script: false,
                  compilable: false,
                },
              },
            },
          },
          {
            _id: '51f9269f-da1b-9749-0950-12d0a2c7e155',
            type: 'HtmlEmbed',
            tag: 'div',
            classes: ['6109b72c-aefe-a83a-143a-40f7277eaecc'],
            children: [],
            v: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" width="100%" height="100%" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><path fill="currentColor" d="M7.41 8.59L12 13.17l4.59-4.58L18 10l-6 6l-6-6l1.41-1.41z"></path></svg>',
            data: {
              insideRTE: false,
              search: { exclude: true },
              embed: {
                type: 'html',
                meta: {
                  html: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" width="100%" height="100%" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><path fill="currentColor" d="M7.41 8.59L12 13.17l4.59-4.58L18 10l-6 6l-6-6l1.41-1.41z"></path></svg>',
                  div: false,
                  iframe: false,
                  script: false,
                  compilable: false,
                },
              },
            },
          },
          {
            _id: '51f9269f-da1b-9749-0950-12d0a2c7e156',
            type: 'DropdownList',
            tag: 'nav',
            classes: ['6109b72c-aefe-a83a-143a-40f7277eaecd'],
            children: [
              '51f9269f-da1b-9749-0950-12d0a2c7e152',
              'c792e265-e192-a315-6c29-944cf965b7ad',
              '51f9269f-da1b-9749-0950-12d0a2c7e159',
            ],
            data: {
              search: { exclude: false },
              xattr: [],
              displayName: '',
              dropdown: { type: 'list' },
              attr: { id: '' },
              visibility: { conditions: [] },
              tag: 'nav',
            },
          },
          {
            _id: '51f9269f-da1b-9749-0950-12d0a2c7e152',
            type: 'FormSelect',
            tag: 'select',
            classes: ['6109b72c-aefe-a83a-143a-40f7277eaed0'],
            children: [],
            data: {
              attr: { id: 'Teams', name: 'Teams', 'data-name': 'Teams', required: false, multiple: false },
              xattr: [{ name: 'fs-combobox-element', value: 'select' }],
              form: {
                name: 'Teams',
                opts: [
                  { t: 'Select one...', v: '' },
                  { t: 'Arsenal', v: 'arsenal' },
                  { t: 'Liverpool', v: 'liverpool' },
                  { t: 'Barcelona', v: 'barcelona' },
                  { t: 'Sevilla', v: 'sevilla' },
                  { t: 'Brentford', v: 'brentford' },
                  { t: 'Zenit', v: 'zenit' },
                  { t: 'Juventus', v: 'juventus' },
                  { t: 'Napoli', v: 'napoli' },
                  { t: 'PSG', v: 'psg' },
                  { t: 'Marseille', v: 'marseille' },
                  { t: 'Monaco', v: 'monaco' },
                  { t: 'Lille', v: 'lille' },
                  { t: 'Nantes', v: 'nantes' },
                  { t: 'Rangers', v: 'rangers' },
                  { t: 'Porto', v: 'porto' },
                  { t: 'Benfica', v: 'benfica' },
                  { t: 'Olympiacos', v: 'olympiacos' },
                  { t: 'Ajax', v: 'ajax' },
                  { t: 'Lazio', v: 'lazio' },
                  { t: 'Freiburg', v: 'freiburg' },
                  { t: 'Atalanta', v: 'atalanta' },
                  { t: 'Sporting', v: 'sporting' },
                  { t: 'Udinese', v: 'udinese' },
                ],
                type: 'select',
              },
            },
          },
          {
            _id: 'c792e265-e192-a315-6c29-944cf965b7ad',
            type: 'Block',
            tag: 'div',
            classes: ['6109b72c-aefe-a83a-143a-40f7277eaece'],
            children: ['b1af4b1e-0005-db80-8d37-78db1245c0e2'],
            data: {
              search: { exclude: false },
              xattr: [{ name: 'fs-combobox-element', value: 'empty' }],
              text: false,
              displayName: '',
              devlink: { runtimeProps: {}, slot: '' },
              attr: { id: '' },
              visibility: { conditions: [] },
              tag: 'div',
            },
          },
          {
            _id: 'b1af4b1e-0005-db80-8d37-78db1245c0e2',
            type: 'Block',
            tag: 'div',
            classes: [],
            children: ['b1af4b1e-0005-db80-8d37-78db1245c0e3'],
            data: {
              search: { exclude: false },
              xattr: [],
              text: true,
              displayName: '',
              devlink: { runtimeProps: {}, slot: '' },
              attr: { id: '' },
              visibility: { conditions: [] },
              tag: 'div',
            },
          },
          { _id: 'b1af4b1e-0005-db80-8d37-78db1245c0e3', text: true, v: 'No results found' },
          {
            _id: '51f9269f-da1b-9749-0950-12d0a2c7e159',
            type: 'Link',
            tag: 'a',
            classes: ['2bff593e-0a8c-8e1f-b37c-d941b7df9f92'],
            children: ['51f9269f-da1b-9749-0950-12d0a2c7e15a', '51f9269f-da1b-9749-0950-12d0a2c7e15b'],
            data: {
              search: { exclude: false },
              xattr: [{ name: 'fs-combobox-element', value: 'option-template' }],
              block: 'inline',
              displayName: '',
              devlink: { runtimeProps: {}, slot: '' },
              attr: { href: '#', id: '' },
              visibility: { conditions: [] },
              button: false,
              link: { mode: 'external' },
            },
          },
          {
            _id: '51f9269f-da1b-9749-0950-12d0a2c7e15a',
            type: 'HtmlEmbed',
            tag: 'div',
            classes: ['6109b72c-aefe-a83a-143a-40f7277eaeca'],
            children: [],
            v: '<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">\n  <path stroke-linecap="round" stroke-linejoin="round" d="M17.25 8.25L21 12m0 0l-3.75 3.75M21 12H3" />\n</svg>',
            data: {
              insideRTE: false,
              search: { exclude: true },
              embed: {
                type: 'html',
                meta: {
                  html: '<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">\n  <path stroke-linecap="round" stroke-linejoin="round" d="M17.25 8.25L21 12m0 0l-3.75 3.75M21 12H3" />\n</svg>',
                  div: false,
                  iframe: false,
                  script: false,
                  compilable: false,
                },
              },
            },
          },
          {
            _id: '51f9269f-da1b-9749-0950-12d0a2c7e15b',
            type: 'Block',
            tag: 'div',
            classes: [],
            children: ['51f9269f-da1b-9749-0950-12d0a2c7e15c'],
            data: {
              search: { exclude: false },
              xattr: [{ name: 'fs-combobox-element', value: 'label' }],
              text: true,
              displayName: '',
              devlink: { runtimeProps: {}, slot: '' },
              attr: { id: '' },
              visibility: { conditions: [] },
              tag: 'div',
            },
          },
          { _id: '51f9269f-da1b-9749-0950-12d0a2c7e15c', text: true, v: 'Option Value' },
        ],
        styles: [
          {
            _id: '6109b72c-aefe-a83a-143a-40f7277eaed0',
            fake: false,
            type: 'class',
            name: 'fs-combobox_select',
            namespace: '',
            comb: '',
            styleLess: 'display: none; margin-bottom: 0px;',
            variants: {},
            children: [],
            createdBy: '5db95a67e381b2189edf0aba',
            selector: null,
          },
          {
            _id: '973a8a90-8d72-c3ed-1af9-319dccecd7d5',
            fake: false,
            type: 'class',
            name: 'fs-combobox_dropdown-toggle',
            namespace: '',
            comb: '',
            styleLess:
              'display: flex; width: 100%; padding-top: 0.5rem; padding-right: 0.75rem; padding-bottom: 0.5rem; padding-left: 1rem; flex-direction: row; justify-content: space-between; align-items: center; grid-column-gap: 0.5rem; grid-row-gap: 0.5rem; background-color: hsla(0, 0.00%, 100.00%, 1.00);',
            variants: {
              'main_focus-visible': {
                styleLess:
                  'outline-color: hsla(0, 0.00%, 67.33%, 1.00); outline-offset: 4px; outline-style: solid; outline-width: 1px;',
              },
            },
            children: [],
            createdBy: '54441c96b0981db6504faf03',
            selector: null,
          },
          {
            _id: '6109b72c-aefe-a83a-143a-40f7277eaecd',
            fake: false,
            type: 'class',
            name: 'fs-combobox_list',
            namespace: '',
            comb: '',
            styleLess: '',
            variants: {
              main_open: {
                styleLess: 'overflow: auto; max-height: 20rem; background-color: hsla(0, 0.00%, 96.00%, 1.00);',
              },
            },
            children: [],
            createdBy: '5db95a67e381b2189edf0aba',
            selector: null,
          },
          {
            _id: 'e56c6b90-c01a-6eb8-8dbc-7a38442d1942',
            fake: false,
            type: 'class',
            name: 'fs-combobox_input',
            namespace: '',
            comb: '',
            styleLess:
              'margin-bottom: 0px; padding-top: 0.25rem; padding-right: 0.25rem; padding-bottom: 0.25rem; padding-left: 0.25rem; border-top-style: none; border-top-width: 1px; border-top-color: black; border-right-style: none; border-right-width: 1px; border-right-color: black; border-bottom-style: none; border-bottom-width: 1px; border-bottom-color: black; border-left-style: none; border-left-width: 1px; border-left-color: black;',
            variants: {},
            children: [],
            createdBy: '54441c96b0981db6504faf03',
            selector: null,
          },
          {
            _id: '2bff593e-0a8c-8e1f-b37c-d941b7df9f92',
            fake: false,
            type: 'class',
            name: 'fs-combobox_option',
            namespace: '',
            comb: '',
            styleLess:
              'display: flex; padding-top: 0.5rem; padding-right: 1rem; padding-bottom: 0.5rem; padding-left: 1rem; align-items: center; border-bottom-style: solid; border-bottom-width: 1px; border-bottom-color: hsla(0, 0.00%, 0.00%, 0.20); background-color: transparent; color: hsla(0, 0.00%, 0.00%, 1.00); font-size: 0.875rem; text-decoration: none;',
            variants: {
              main_hover: {
                styleLess:
                  'outline-color: hsla(222, 82.57%, 57.25%, 1.00); outline-offset: -0.125rem; outline-style: solid; outline-width: 0.125rem;',
              },
              main_current: {
                styleLess: 'background-color: hsla(222, 82.57%, 57.25%, 1.00); color: hsla(222, 0.00%, 100.00%, 1.00);',
              },
              main_focus: {
                styleLess:
                  'outline-color: hsla(222, 82.57%, 57.25%, 1.00); outline-offset: -0.125rem; outline-style: solid; outline-width: 0.125rem;',
              },
            },
            children: [],
            createdBy: '54441c96b0981db6504faf03',
            selector: null,
          },
          {
            _id: '6109b72c-aefe-a83a-143a-40f7277eaece',
            fake: false,
            type: 'class',
            name: 'fs-combobox_empty',
            namespace: '',
            comb: '',
            styleLess:
              'padding-top: 0.5rem; padding-right: 1rem; padding-bottom: 0.5rem; padding-left: 1rem; color: hsla(0, 0.00%, 0.00%, 1.00); font-size: 0.875rem;',
            variants: {},
            children: [],
            createdBy: '5db95a67e381b2189edf0aba',
            selector: null,
          },
          {
            _id: '1f84ad3a-62cb-466f-570c-99c02ba6b104',
            fake: false,
            type: 'class',
            name: 'fs-combobox_dropdown',
            namespace: '',
            comb: '',
            styleLess: 'width: 18rem;',
            variants: {},
            children: [],
            createdBy: '54441c96b0981db6504faf03',
            selector: null,
          },
          {
            _id: '6109b72c-aefe-a83a-143a-40f7277eaec9',
            fake: false,
            type: 'class',
            name: 'fs-combobox_reset',
            namespace: '',
            comb: '',
            styleLess:
              'width: 1.25rem; height: 1.25rem; flex-direction: column; justify-content: center; flex-grow: 0; flex-shrink: 0; flex-basis: auto; color: hsla(0, 0.00%, 0.00%, 1.00); cursor: pointer;',
            variants: {},
            children: [],
            createdBy: '5db95a67e381b2189edf0aba',
            selector: null,
          },
          {
            _id: '6109b72c-aefe-a83a-143a-40f7277eaecc',
            fake: false,
            type: 'class',
            name: 'fs-combobox_arrow',
            namespace: '',
            comb: '',
            styleLess:
              'display: flex; width: 1.5rem; flex-direction: column; justify-content: center; flex-grow: 0; flex-shrink: 0; flex-basis: auto; color: hsla(0, 0.00%, 0.00%, 1.00);',
            variants: {},
            children: [],
            createdBy: '5db95a67e381b2189edf0aba',
            selector: null,
          },
          {
            _id: '6109b72c-aefe-a83a-143a-40f7277eaeca',
            fake: false,
            type: 'class',
            name: 'fs-combobox_icon',
            namespace: '',
            comb: '',
            styleLess: 'display: flex; width: 1rem; margin-right: 0.5rem; flex-direction: column;',
            variants: {},
            children: [],
            createdBy: '5db95a67e381b2189edf0aba',
            selector: null,
          },
        ],
        assets: [],
        ix1: [],
        ix2: { interactions: [], events: [], actionLists: [] },
      },
      meta: {
        unlinkedSymbolCount: 0,
        droppedLinks: 0,
        dynBindRemovedCount: 0,
        dynListBindRemovedCount: 0,
        paginationRemovedCount: 0,
      },
    },
  },
];

export default examples;
