import {
  BUTTON,
  COLLECTION_ITEM,
  DIV_BLOCK,
  HEADING,
  IMAGE,
  LINK_BLOCK,
  PARAGRAPH,
  TEXT_BLOCK,
  TEXT_ELEMENT,
  TEXT_LINK,
} from '$global/constants/webflow-selectors';
import type { AttributeSchema } from '$global/types/schema';

import {
  CONTENT_ELEMENT_KEY,
  DEFAULT_HEIGHT_SETTING_KEY,
  DEFAULT_WIDTH_SETTING_KEY,
  FACEBOOK_ELEMENT_KEY,
  FACEBOOK_HASHTAG_ELEMENT_KEY,
  HEIGHT_SETTING_KEY,
  LINKEDIN_ELEMENT_KEY,
  PINTEREST_DESCRIPTION_ELEMENT_KEY,
  PINTEREST_ELEMENT_KEY,
  PINTEREST_IMAGE_ELEMENT_KEY,
  REDDIT_ELEMENT_KEY,
  TELEGRAM_ELEMENT_KEY,
  TWITTER_ELEMENT_KEY,
  TWITTER_HASHTAG_ELEMENT_KEY,
  TWITTER_USERNAME_ELEMENT_KEY,
  URL_ELEMENT_KEY,
  WIDTH_SETTING_KEY,
} from './../src/utils/constants';

const schema: AttributeSchema = {
  elements: [
    {
      key: FACEBOOK_ELEMENT_KEY,
      description: 'Defines a Facebook social button',
      requiresInstance: true,
      multiplesInInstance: true,
      appliedTo: [BUTTON, LINK_BLOCK, TEXT_LINK, TEXT_ELEMENT, DIV_BLOCK],
      conditions: [],
      required: false,
      caseInsensitive: true,
    },
    {
      key: TWITTER_ELEMENT_KEY,
      description: 'Defines a Twitter social button',
      requiresInstance: true,
      multiplesInInstance: true,
      appliedTo: [BUTTON, LINK_BLOCK, TEXT_LINK, TEXT_ELEMENT, DIV_BLOCK],
      conditions: [],
      required: false,
      caseInsensitive: true,
    },
    {
      key: PINTEREST_ELEMENT_KEY,
      description: 'Defines a Pinterest social button',
      requiresInstance: true,
      multiplesInInstance: true,
      appliedTo: [BUTTON, LINK_BLOCK, TEXT_LINK, TEXT_ELEMENT, DIV_BLOCK],
      conditions: [],
      required: false,
      caseInsensitive: true,
    },
    {
      key: LINKEDIN_ELEMENT_KEY,
      description: 'Defines a Linkedin social button',
      requiresInstance: true,
      multiplesInInstance: true,
      appliedTo: [BUTTON, LINK_BLOCK, TEXT_LINK, TEXT_ELEMENT, DIV_BLOCK],
      conditions: [],
      required: false,
      caseInsensitive: true,
    },
    {
      key: TELEGRAM_ELEMENT_KEY,
      description: 'Defines a Telegram social button',
      requiresInstance: true,
      multiplesInInstance: true,
      appliedTo: [BUTTON, LINK_BLOCK, TEXT_LINK, TEXT_ELEMENT, DIV_BLOCK],
      conditions: [],
      required: false,
      caseInsensitive: true,
    },
    {
      key: REDDIT_ELEMENT_KEY,
      description: 'Defines a Reddit social button',
      requiresInstance: true,
      multiplesInInstance: true,
      appliedTo: [BUTTON, LINK_BLOCK, TEXT_LINK, TEXT_ELEMENT, DIV_BLOCK],
      conditions: [],
      required: false,
      caseInsensitive: true,
    },
    {
      key: CONTENT_ELEMENT_KEY,
      description: 'Defines the Content to be share into social media',
      requiresInstance: true,
      multiplesInInstance: false,
      appliedTo: [TEXT_BLOCK, HEADING, PARAGRAPH],
      conditions: [],
      required: false,
      scope: COLLECTION_ITEM,
    },
    {
      key: URL_ELEMENT_KEY,
      description: 'Defines a custom URL to be share into social media',
      requiresInstance: true,
      multiplesInInstance: false,
      appliedTo: [TEXT_BLOCK, HEADING, PARAGRAPH, TEXT_LINK],
      conditions: [],
      required: false,
      scope: COLLECTION_ITEM,
    },
    {
      key: FACEBOOK_HASHTAG_ELEMENT_KEY,
      description: 'Defines Facebook hashtags',
      requiresInstance: true,
      multiplesInInstance: false,
      appliedTo: [TEXT_BLOCK, HEADING, PARAGRAPH, TEXT_LINK],
      conditions: [],
      required: false,
      scope: COLLECTION_ITEM,
    },
    {
      key: TWITTER_HASHTAG_ELEMENT_KEY,
      description: 'Defines Twitter hashtags',
      requiresInstance: true,
      multiplesInInstance: false,
      appliedTo: [TEXT_BLOCK, HEADING, PARAGRAPH, TEXT_LINK],
      conditions: [],
      required: false,
      scope: COLLECTION_ITEM,
    },
    {
      key: TWITTER_USERNAME_ELEMENT_KEY,
      description: 'Defines Twitter username',
      requiresInstance: true,
      multiplesInInstance: false,
      appliedTo: [TEXT_BLOCK, HEADING, PARAGRAPH, TEXT_LINK],
      conditions: [],
      required: false,
      scope: COLLECTION_ITEM,
    },
    {
      key: PINTEREST_IMAGE_ELEMENT_KEY,
      description: 'Defines Pinterest image',
      requiresInstance: true,
      multiplesInInstance: false,
      appliedTo: [IMAGE],
      conditions: [],
      required: false,
      scope: COLLECTION_ITEM,
    },
    {
      key: PINTEREST_DESCRIPTION_ELEMENT_KEY,
      description: 'Defines Pinterest description',
      requiresInstance: true,
      multiplesInInstance: false,
      appliedTo: [TEXT_BLOCK, HEADING, PARAGRAPH],
      conditions: [],
      required: false,
      scope: COLLECTION_ITEM,
    },
  ],
  settings: [
    {
      key: WIDTH_SETTING_KEY,
      description: 'Defines the width of popup window.',
      appliedTo: {
        elements: [
          FACEBOOK_ELEMENT_KEY,
          TWITTER_ELEMENT_KEY,
          LINKEDIN_ELEMENT_KEY,
          TELEGRAM_ELEMENT_KEY,
          REDDIT_ELEMENT_KEY,
          PINTEREST_ELEMENT_KEY,
        ],
      },
      conditions: [],
      value: {
        type: 'int',
        default: DEFAULT_WIDTH_SETTING_KEY.toString(),
      },
    },
    {
      key: HEIGHT_SETTING_KEY,
      description: 'Defines the height of popup window.',
      appliedTo: {
        elements: [
          FACEBOOK_ELEMENT_KEY,
          TWITTER_ELEMENT_KEY,
          LINKEDIN_ELEMENT_KEY,
          TELEGRAM_ELEMENT_KEY,
          REDDIT_ELEMENT_KEY,
          PINTEREST_ELEMENT_KEY,
        ],
      },
      conditions: [],
      value: {
        type: 'int',
        default: DEFAULT_HEIGHT_SETTING_KEY.toString(),
      },
    },
  ],
};

export default schema;
