import type { AttributeExamples } from '$global/types/examples';

const examples: AttributeExamples = [
  {
    title: 'Code Highlight',
    description: 'Highlights a code block using the Webflow theme.',
    data: {
      type: '@webflow/XscpData',
      payload: {
        nodes: [
          {
            _id: 'd990f089-4d9d-ed93-70b1-d1b7b2bfdc8e',
            type: 'RichText',
            tag: 'div',
            classes: ['7a7204b8-a1e7-dc94-64a3-f51aa86eda74'],
            children: [
              'd990f089-4d9d-ed93-70b1-d1b7b2bfdc8f',
              'a10d8b76-b66f-73b9-8488-bc409e21ab20',
              'd990f089-4d9d-ed93-70b1-d1b7b2bfdc91',
              '480b4b78-6a5c-c9ea-0db9-400ae41fb594',
              '85cd7cf3-0645-43b6-a08a-44382c7d9cb6',
              '55b76110-a131-e351-23fd-c86565f72a52',
              'd990f089-4d9d-ed93-70b1-d1b7b2bfdc93',
              '411d981b-d66c-41d9-6aac-585b7913d24d',
              'd990f089-4d9d-ed93-70b1-d1b7b2bfdc95',
              'de2d26db-94c5-2ccb-a434-449951a9f769',
              'd990f089-4d9d-ed93-70b1-d1b7b2bfdc97',
              '3610e31c-864c-fb03-de1c-925d7fefaafd',
              'd990f089-4d9d-ed93-70b1-d1b7b2bfdc99',
            ],
            data: {
              search: { exclude: false },
              xattr: [
                { name: 'fs-codehighlight-element', value: 'code' },
                { name: 'fs-codehighlight-theme', value: 'webflow' },
              ],
              displayName: '',
              attr: { id: '' },
              visibility: { conditions: [] },
              tag: 'div',
              rich: true,
            },
          },
          {
            _id: 'd990f089-4d9d-ed93-70b1-d1b7b2bfdc8f',
            type: 'Heading',
            tag: 'h2',
            classes: [],
            children: ['d990f089-4d9d-ed93-70b1-d1b7b2bfdc90'],
            data: {
              tag: 'h2',
              displayName: '',
              attr: { id: '' },
              xattr: [],
              search: { exclude: false },
              visibility: { conditions: [] },
            },
          },
          { _id: 'd990f089-4d9d-ed93-70b1-d1b7b2bfdc90', text: true, v: 'What’s a Rich Text element?' },
          {
            _id: 'a10d8b76-b66f-73b9-8488-bc409e21ab20',
            type: 'Paragraph',
            tag: 'p',
            classes: [],
            children: ['a10d8b76-b66f-73b9-8488-bc409e21ab21'],
            data: {
              displayName: '',
              attr: { id: '' },
              xattr: [],
              search: { exclude: false },
              visibility: { conditions: [] },
            },
          },
          { _id: 'a10d8b76-b66f-73b9-8488-bc409e21ab21', text: true, v: '‍' },
          {
            _id: 'd990f089-4d9d-ed93-70b1-d1b7b2bfdc91',
            type: 'Paragraph',
            tag: 'p',
            classes: [],
            children: ['d990f089-4d9d-ed93-70b1-d1b7b2bfdc92'],
            data: {
              displayName: '',
              attr: { id: '' },
              xattr: [],
              search: { exclude: false },
              visibility: { conditions: [] },
            },
          },
          {
            _id: 'd990f089-4d9d-ed93-70b1-d1b7b2bfdc92',
            text: true,
            v: 'The rich text element allows you to create and format headings, paragraphs, blockquotes, images, and video all in one place instead of having to add and format them individually. Just double-click and easily create content.',
          },
          {
            _id: '480b4b78-6a5c-c9ea-0db9-400ae41fb594',
            type: 'Paragraph',
            tag: 'p',
            classes: [],
            children: ['480b4b78-6a5c-c9ea-0db9-400ae41fb595'],
            data: {
              displayName: '',
              attr: { id: '' },
              xattr: [],
              search: { exclude: false },
              visibility: { conditions: [] },
            },
          },
          { _id: '480b4b78-6a5c-c9ea-0db9-400ae41fb595', text: true, v: '‍' },
          {
            _id: '85cd7cf3-0645-43b6-a08a-44382c7d9cb6',
            type: 'HtmlEmbed',
            tag: 'div',
            classes: [],
            children: [],
            v: "<pre><code>&lt;script>\n  /**\n   * Writes the current year to all elements that match the selector.\n   */\n  function setCurrentYear() {\n    const YEAR_ELEMENTS_SELECTOR = '[fs-hacks-element=\"year\"]';\n\n    const yearElements = document.querySelectorAll(YEAR_ELEMENTS_SELECTOR);\n    const currentYear = new Date().getFullYear().toString();\n\n    yearElements.forEach((yearElement) => {\n      yearElement.textContent = currentYear;\n    });\n  }\n  \n  document.addEventListener('DOMContentLoaded', setCurrentYear);\n&lt;/script></code></pre>",
            data: {
              insideRTE: true,
              search: { exclude: true },
              embed: {
                type: 'html',
                meta: {
                  html: "<pre><code>&lt;script>\n  /**\n   * Writes the current year to all elements that match the selector.\n   */\n  function setCurrentYear() {\n    const YEAR_ELEMENTS_SELECTOR = '[fs-hacks-element=\"year\"]';\n\n    const yearElements = document.querySelectorAll(YEAR_ELEMENTS_SELECTOR);\n    const currentYear = new Date().getFullYear().toString();\n\n    yearElements.forEach((yearElement) => {\n      yearElement.textContent = currentYear;\n    });\n  }\n  \n  document.addEventListener('DOMContentLoaded', setCurrentYear);\n&lt;/script></code></pre>",
                  div: false,
                  iframe: false,
                  script: false,
                  compilable: false,
                },
              },
            },
          },
          {
            _id: '55b76110-a131-e351-23fd-c86565f72a52',
            type: 'Paragraph',
            tag: 'p',
            classes: [],
            children: ['55b76110-a131-e351-23fd-c86565f72a53'],
            data: {
              displayName: '',
              attr: { id: '' },
              xattr: [],
              search: { exclude: false },
              visibility: { conditions: [] },
            },
          },
          { _id: '55b76110-a131-e351-23fd-c86565f72a53', text: true, v: '‍' },
          {
            _id: 'd990f089-4d9d-ed93-70b1-d1b7b2bfdc93',
            type: 'Heading',
            tag: 'h3',
            classes: [],
            children: ['d990f089-4d9d-ed93-70b1-d1b7b2bfdc94'],
            data: {
              tag: 'h3',
              displayName: '',
              attr: { id: '' },
              xattr: [],
              search: { exclude: false },
              visibility: { conditions: [] },
            },
          },
          { _id: 'd990f089-4d9d-ed93-70b1-d1b7b2bfdc94', text: true, v: 'Static and dynamic content editing' },
          {
            _id: '411d981b-d66c-41d9-6aac-585b7913d24d',
            type: 'Paragraph',
            tag: 'p',
            classes: [],
            children: ['411d981b-d66c-41d9-6aac-585b7913d24e'],
            data: {
              displayName: '',
              attr: { id: '' },
              xattr: [],
              search: { exclude: false },
              visibility: { conditions: [] },
            },
          },
          { _id: '411d981b-d66c-41d9-6aac-585b7913d24e', text: true, v: '‍' },
          {
            _id: 'd990f089-4d9d-ed93-70b1-d1b7b2bfdc95',
            type: 'Paragraph',
            tag: 'p',
            classes: [],
            children: ['d990f089-4d9d-ed93-70b1-d1b7b2bfdc96'],
            data: {
              displayName: '',
              attr: { id: '' },
              xattr: [],
              search: { exclude: false },
              visibility: { conditions: [] },
            },
          },
          {
            _id: 'd990f089-4d9d-ed93-70b1-d1b7b2bfdc96',
            text: true,
            v: 'A rich text element can be used with static or dynamic content. For static content, just drop it into any page and begin editing. For dynamic content, add a rich text field to any collection and then connect a rich text element to that field in the settings panel. Voila!',
          },
          {
            _id: 'de2d26db-94c5-2ccb-a434-449951a9f769',
            type: 'Paragraph',
            tag: 'p',
            classes: [],
            children: ['de2d26db-94c5-2ccb-a434-449951a9f76a'],
            data: {
              displayName: '',
              attr: { id: '' },
              xattr: [],
              search: { exclude: false },
              visibility: { conditions: [] },
            },
          },
          { _id: 'de2d26db-94c5-2ccb-a434-449951a9f76a', text: true, v: '‍' },
          {
            _id: 'd990f089-4d9d-ed93-70b1-d1b7b2bfdc97',
            type: 'Heading',
            tag: 'h3',
            classes: [],
            children: ['d990f089-4d9d-ed93-70b1-d1b7b2bfdc98'],
            data: {
              tag: 'h3',
              displayName: '',
              attr: { id: '' },
              xattr: [],
              search: { exclude: false },
              visibility: { conditions: [] },
            },
          },
          {
            _id: 'd990f089-4d9d-ed93-70b1-d1b7b2bfdc98',
            text: true,
            v: 'How to customize formatting for each rich text',
          },
          {
            _id: '3610e31c-864c-fb03-de1c-925d7fefaafd',
            type: 'Paragraph',
            tag: 'p',
            classes: [],
            children: ['3610e31c-864c-fb03-de1c-925d7fefaafe'],
            data: {
              displayName: '',
              attr: { id: '' },
              xattr: [],
              search: { exclude: false },
              visibility: { conditions: [] },
            },
          },
          { _id: '3610e31c-864c-fb03-de1c-925d7fefaafe', text: true, v: '‍' },
          {
            _id: 'd990f089-4d9d-ed93-70b1-d1b7b2bfdc99',
            type: 'Paragraph',
            tag: 'p',
            classes: [],
            children: ['d990f089-4d9d-ed93-70b1-d1b7b2bfdc9a'],
            data: {
              displayName: '',
              attr: { id: '' },
              xattr: [],
              search: { exclude: false },
              visibility: { conditions: [] },
            },
          },
          {
            _id: 'd990f089-4d9d-ed93-70b1-d1b7b2bfdc9a',
            text: true,
            v: 'Headings, paragraphs, blockquotes, figures, images, and figure captions can all be styled after a class is added to the rich text element using the "When inside of" nested selector system.',
          },
        ],
        styles: [
          {
            _id: '7a7204b8-a1e7-dc94-64a3-f51aa86eda74',
            fake: false,
            type: 'class',
            name: 'fs-codehighlight_richtext',
            namespace: '',
            comb: '',
            styleLess: '',
            variants: {},
            children: [],
            selector: null,
          },
        ],
        assets: [],
        ix1: [],
        ix2: { interactions: [], events: [], actionLists: [] },
      },
      meta: {
        unlinkedSymbolCount: 0,
        droppedLinks: 0,
        dynBindRemovedCount: 0,
        dynListBindRemovedCount: 0,
        paginationRemovedCount: 0,
      },
    },
  },
];

export default examples;
